const LANG_ES = {
  code: 'es',
  name: 'Español',
  cards: [
    // --- FOOD (50) ---
    {topic:"food",word:"agua",transcription:"[ˈa.ɣwa]",translation:"вода",example:"El agua está fría.",exampleTranslation:"Вода холодная."},
    {topic:"food",word:"pan",transcription:"[pan]",translation:"хлеб",example:"Yo como pan.",exampleTranslation:"Я ем хлеб."},
    {topic:"food",word:"leche",transcription:"[ˈle.tʃe]",translation:"молоко",example:"La leche es blanca.",exampleTranslation:"Молоко белое."},
    {topic:"food",word:"manzana",transcription:"[manˈsa.na]",translation:"яблоко",example:"La manzana es roja.",exampleTranslation:"Яблоко красное."},
    {topic:"food",word:"queso",transcription:"[ˈke.so]",translation:"сыр",example:"El queso es bueno.",exampleTranslation:"Сыр хороший."},
    {topic:"food",word:"carne",transcription:"[ˈkaɾ.ne]",translation:"мясо",example:"No como carne.",exampleTranslation:"Я не ем мясо."},
    {topic:"food",word:"pescado",transcription:"[pesˈka.ðo]",translation:"рыба",example:"El pescado es fresco.",exampleTranslation:"Рыба свежая."},
    {topic:"food",word:"huevo",transcription:"[ˈwe.βo]",translation:"яйцо",example:"Quiero un huevo.",exampleTranslation:"Я хочу яйцо."},
    {topic:"food",word:"arroz",transcription:"[aˈros]",translation:"рис",example:"El arroz está rico.",exampleTranslation:"Рис вкусный."},
    {topic:"food",word:"sopa",transcription:"[ˈso.pa]",translation:"суп",example:"La sopa está caliente.",exampleTranslation:"Суп горячий."},
    {topic:"food",word:"fruta",transcription:"[ˈfɾu.ta]",translation:"фрукт",example:"Me gusta la fruta.",exampleTranslation:"Мне нравятся фрукты."},
    {topic:"food",word:"verdura",transcription:"[beɾˈðu.ɾa]",translation:"овощ",example:"La verdura es sana.",exampleTranslation:"Овощи полезны."},
    {topic:"food",word:"café",transcription:"[kaˈfe]",translation:"кофе",example:"Tomo café por la mañana.",exampleTranslation:"Я пью кофе по утрам."},
    {topic:"food",word:"té",transcription:"[te]",translation:"чай",example:"El té está muy dulce.",exampleTranslation:"Чай очень сладкий."},
    {topic:"food",word:"azúcar",transcription:"[aˈsu.kaɾ]",translation:"сахар",example:"Necesito azúcar.",exampleTranslation:"Мне нужен сахар."},
    {topic:"food",word:"sal",transcription:"[sal]",translation:"соль",example:"La sal está en la mesa.",exampleTranslation:"Соль на столе."},
    {topic:"food",word:"aceite",transcription:"[aˈsei̯.te]",translation:"масло (растительное)",example:"El aceite es de oliva.",exampleTranslation:"Масло оливковое."},
    {topic:"food",word:"mantequilla",transcription:"[man.teˈki.ʎa]",translation:"масло (сливочное)",example:"La mantequilla se derrite.",exampleTranslation:"Сливочное масло тает."},
    {topic:"food",word:"pollo",transcription:"[ˈpo.ʎo]",translation:"курица",example:"El pollo está cocinado.",exampleTranslation:"Курица приготовлена."},
    {topic:"food",word:"tomate",transcription:"[toˈma.te]",translation:"помидор",example:"El tomate es rojo.",exampleTranslation:"Помидор красный."},
    {topic:"food",word:"patata",transcription:"[paˈta.ta]",translation:"картофель",example:"La patata está frita.",exampleTranslation:"Картошка пожарена."},
    {topic:"food",word:"cebolla",transcription:"[seˈβo.ʎa]",translation:"лук",example:"La cebolla pica.",exampleTranslation:"Жжёт от лука."},
    {topic:"food",word:"ajo",transcription:"[ˈa.xo]",translation:"чеснок",example:"El ajo da sabor.",exampleTranslation:"Чеснок даёт вкус."},
    {topic:"food",word:"zanahoria",transcription:"[sa.naˈo.ɾja]",translation:"морковь",example:"La zanahoria es naranja.",exampleTranslation:"Морковь оранжевая."},
    {topic:"food",word:"ensalada",transcription:"[en.saˈla.ða]",translation:"салат",example:"Como una ensalada grande.",exampleTranslation:"Я ем большой салат."},
    {topic:"food",word:"pasta",transcription:"[ˈpas.ta]",translation:"паста / макароны",example:"La pasta está lista.",exampleTranslation:"Паста готова."},
    {topic:"food",word:"pizza",transcription:"[ˈpit.sa]",translation:"пицца",example:"La pizza es caliente.",exampleTranslation:"Пицца горячая."},
    {topic:"food",word:"postre",transcription:"[ˈpos.tɾe]",translation:"десерт",example:"El postre es dulce.",exampleTranslation:"Десерт сладкий."},
    {topic:"food",word:"pastel",transcription:"[pasˈtel]",translation:"торт",example:"El pastel es de chocolate.",exampleTranslation:"Торт шоколадный."},
    {topic:"food",word:"helado",transcription:"[eˈla.ðo]",translation:"мороженое",example:"El helado es frío.",exampleTranslation:"Мороженое холодное."},
    {topic:"food",word:"chocolate",transcription:"[tʃo.koˈla.te]",translation:"шоколад",example:"Me encanta el chocolate.",exampleTranslation:"Я обожаю шоколад."},
    {topic:"food",word:"galleta",transcription:"[ɡaˈʎe.ta]",translation:"печенье",example:"Tomo una galleta.",exampleTranslation:"Я беру печенье."},
    {topic:"food",word:"zumo",transcription:"[ˈsu.mo]",translation:"сок",example:"Un zumo de naranja, por favor.",exampleTranslation:"Сок апельсиновый, пожалуйста."},
    {topic:"food",word:"cerveza",transcription:"[seɾˈβe.sa]",translation:"пиво",example:"La cerveza está fría.",exampleTranslation:"Пиво холодное."},
    {topic:"food",word:"vino",transcription:"[ˈbi.no]",translation:"вино",example:"Prefiero vino tinto.",exampleTranslation:"Я предпочитаю красное вино."},
    {topic:"food",word:"jamón",transcription:"[xaˈmon]",translation:"ветчина / хамон",example:"El jamón está rico.",exampleTranslation:"Хамон вкусный."},
    {topic:"food",word:"miel",transcription:"[mjel]",translation:"мёд",example:"La miel es dulce.",exampleTranslation:"Мёд сладкий."},
    {topic:"food",word:"pimienta",transcription:"[piˈmjen.ta]",translation:"перец (специя)",example:"Añado pimienta.",exampleTranslation:"Я добавляю перец."},
    {topic:"food",word:"limón",transcription:"[liˈmon]",translation:"лимон",example:"El limón es ácido.",exampleTranslation:"Лимон кислый."},
    {topic:"food",word:"naranja",transcription:"[naˈɾaŋ.xa]",translation:"апельсин",example:"La naranja es dulce.",exampleTranslation:"Апельсин сладкий."},
    {topic:"food",word:"plátano",transcription:"[ˈpla.ta.no]",translation:"банан",example:"El plátano es amarillo.",exampleTranslation:"Банан жёлтый."},
    {topic:"food",word:"uva",transcription:"[ˈu.βa]",translation:"виноград",example:"La uva es verde.",exampleTranslation:"Виноград зелёный."},
    {topic:"food",word:"fresa",transcription:"[ˈfɾe.sa]",translation:"клубника",example:"La fresa es roja.",exampleTranslation:"Клубника красная."},
    {topic:"food",word:"sándwich",transcription:"[ˈsan.dwitʃ]",translation:"бутерброд",example:"Quiero un sándwich.",exampleTranslation:"Я хочу бутерброд."},
    {topic:"food",word:"mermelada",transcription:"[meɾ.meˈla.ða]",translation:"джема",example:"La mermelada es de fresa.",exampleTranslation:"Джем из клубники."},
    {topic:"food",word:"harina",transcription:"[aˈɾi.na]",translation:"мука",example:"Compro harina.",exampleTranslation:"Я покупаю муку."},
    {topic:"food",word:"nuez",transcription:"[nwes]",translation:"грецкий орех",example:"La nuez es sana.",exampleTranslation:"Орех полезен."},
    {topic:"food",word:"mantequilla de cacahuete",transcription:"[man.teˈki.ʎa ðe ka.kaˈwe.te]",translation:"арахисовое масло",example:"Me gusta la mantequilla de cacahuete.",exampleTranslation:"Мне нравится арахисовое масло."},
    {topic:"food",word:"yogur",transcription:"[joˈɣuɾ]",translation:"йогурт",example:"El yogur es de fresa.",exampleTranslation:"Йогурт клубничный."},
    {topic:"food",word:"salsa",transcription:"[ˈsal.sa]",translation:"соус",example:"La salsa picante es buena.",exampleTranslation:"Острый соус хороший."},

    // --- HOME (50) ---
    {topic:"home",word:"casa",transcription:"[ˈka.sa]",translation:"дом",example:"La casa es grande.",exampleTranslation:"Дом большой."},
    {topic:"home",word:"piso",transcription:"[ˈpi.so]",translation:"квартира",example:"Mi piso es bonito.",exampleTranslation:"Моя квартира красивая."},
    {topic:"home",word:"habitación",transcription:"[a.βi.taˈsjon]",translation:"комната",example:"La habitación es clara.",exampleTranslation:"Комната светлая."},
    {topic:"home",word:"cocina",transcription:"[koˈsi.na]",translation:"кухня",example:"La cocina es limpia.",exampleTranslation:"Кухня чистая."},
    {topic:"home",word:"baño",transcription:"[ˈba.ɲo]",translation:"ванная комната",example:"El baño está al fondo.",exampleTranslation:"Ванная в конце."},
    {topic:"home",word:"salón",transcription:"[saˈlon]",translation:"гостиная",example:"El salón es amplio.",exampleTranslation:"Гостиная просторная."},
    {topic:"home",word:"puerta",transcription:"[ˈpweɾ.ta]",translation:"дверь",example:"La puerta está cerrada.",exampleTranslation:"Дверь закрыта."},
    {topic:"home",word:"ventana",transcription:"[benˈta.na]",translation:"окно",example:"Abro la ventana.",exampleTranslation:"Я открываю окно."},
    {topic:"home",word:"pared",transcription:"[paˈɾeð]",translation:"стена",example:"La pared es blanca.",exampleTranslation:"Стена белая."},
    {topic:"home",word:"suelo",transcription:"[ˈswe.lo]",translation:"пол",example:"El suelo está limpio.",exampleTranslation:"Пол чистый."},
    {topic:"home",word:"techo",transcription:"[ˈte.tʃo]",translation:"потолок",example:"El techo es alto.",exampleTranslation:"Потолок высокий."},
    {topic:"home",word:"mesa",transcription:"[ˈme.sa]",translation:"стол",example:"La mesa es de madera.",exampleTranslation:"Стол из дерева."},
    {topic:"home",word:"silla",transcription:"[ˈsi.ʎa]",translation:"стул",example:"La silla es cómoda.",exampleTranslation:"Стул удобный."},
    {topic:"home",word:"sofá",transcription:"[soˈfa]",translation:"диван",example:"Me siento en el sofá.",exampleTranslation:"Я сажусь на диван."},
    {topic:"home",word:"cama",transcription:"[ˈka.ma]",translation:"кровать",example:"La cama es grande.",exampleTranslation:"Кровать большая."},
    {topic:"home",word:"armario",transcription:"[aɾˈma.ɾjo]",translation:"шкаф",example:"La ropa está en el armario.",exampleTranslation:"Одежда в шкафу."},
    {topic:"home",word:"lámpara",transcription:"[ˈlam.pa.ɾa]",translation:"лампа",example:"La lámpara ilumina bien.",exampleTranslation:"Лампа хорошо светит."},
    {topic:"home",word:"espejo",transcription:"[esˈpe.xo]",translation:"зеркало",example:"Me miro en el espejo.",exampleTranslation:"Я смотрю в зеркало."},
    {topic:"home",word:"televisión",transcription:"[te.le.βiˈsjon]",translation:"телевизор",example:"Veo la televisión.",exampleTranslation:"Я смотрю телевизор."},
    {topic:"home",word:"nevera",transcription:"[neˈβe.ɾa]",translation:"холодильник",example:"La comida está en la nevera.",exampleTranslation:"Еда в холодильнике."},
    {topic:"home",word:"horno",transcription:"[ˈoɾ.no]",translation:"духовка",example:"El horno está caliente.",exampleTranslation:"Духовка горячая."},
    {topic:"home",word:"microondas",transcription:"[mi.kɾoˈon.das]",translation:"микроволновка",example:"Caliento la sopa en el microondas.",exampleTranslation:"Я грею суп в микроволновке."},
    {topic:"home",word:"lavadora",transcription:"[la.βaˈðo.ɾa]",translation:"стиральная машина",example:"La lavadora funciona.",exampleTranslation:"Стиральная машина работает."},
    {topic:"home",word:"ducha",transcription:"[ˈdu.tʃa]",translation:"душ",example:"Tomo una ducha.",exampleTranslation:"Я принимаю душ."},
    {topic:"home",word:"toalla",transcription:"[toˈa.ʎa]",translation:"полотенце",example:"La toalla está seca.",exampleTranslation:"Полотенце сухое."},
    {topic:"home",word:"almohada",transcription:"[al.moˈa.ða]",translation:"подушка",example:"La almohada es suave.",exampleTranslation:"Подушка мягкая."},
    {topic:"home",word:"manta",transcription:"[ˈman.ta]",translation:"одеяло",example:"La manta da calor.",exampleTranslation:"Одеяло согревает."},
    {topic:"home",word:"sábana",transcription:"[ˈsa.βa.na]",translation:"простыня",example:"La sábana es blanca.",exampleTranslation:"Простыня белая."},
    {topic:"home",word:"alfombra",transcription:"[alˈfom.bɾa]",translation:"ковёр",example:"La alfombra está en el suelo.",exampleTranslation:"Ковёр на полу."},
    {topic:"home",word:"cortina",transcription:"[koɾˈti.na]",translation:"штора",example:"Cierro la cortina.",exampleTranslation:"Я закрываю штору."},
    {topic:"home",word:"llave",transcription:"[ˈʎa.βe]",translation:"ключ",example:"Tengo la llave.",exampleTranslation:"У меня есть ключ."},
    {topic:"home",word:"vaso",transcription:"[ˈba.so]",translation:"стакан",example:"Un vaso de agua, por favor.",exampleTranslation:"Стакан воды, пожалуйста."},
    {topic:"home",word:"plato",transcription:"[ˈpla.to]",translation:"тарелка",example:"El plato está limpio.",exampleTranslation:"Тарелка чистая."},
    {topic:"home",word:"cuchara",transcription:"[kuˈtʃa.ɾa]",translation:"ложка",example:"Necesito una cuchara.",exampleTranslation:"Мне нужна ложка."},
    {topic:"home",word:"tenedor",transcription:"[te.neˈðoɾ]",translation:"вилка",example:"Tengo un tenedor.",exampleTranslation:"У меня есть вилка."},
    {topic:"home",word:"cuchillo",transcription:"[kuˈtʃi.ʎo]",translation:"нож",example:"El cuchillo corta bien.",exampleTranslation:"Нож хорошо режет."},
    {topic:"home",word:"taza",transcription:"[ˈta.sa]",translation:"чашка",example:"Una taza de café, por favor.",exampleTranslation:"Чашка кофе, пожалуйста."},
    {topic:"home",word:"sartén",transcription:"[saɾˈten]",translation:"сковорода",example:"La sartén es negra.",exampleTranslation:"Сковорода чёрная."},
    {topic:"home",word:"olla",transcription:"[ˈo.ʎa]",translation:"кастрюля",example:"La olla está llena.",exampleTranslation:"Кастрюля полная."},
    {topic:"home",word:"escoba",transcription:"[esˈko.βa]",translation:"метла / веник",example:"Uso la escoba.",exampleTranslation:"Я использую веник."},
    {topic:"home",word:"jardín",transcription:"[xaɾˈðin]",translation:"сад",example:"El jardín es lindo.",exampleTranslation:"Сад красивый."},
    {topic:"home",word:"balcón",transcription:"[balˈkon]",translation:"балкон",example:"El balcón es pequeño.",exampleTranslation:"Балкон маленький."},
    {topic:"home",word:"garaje",transcription:"[ɡaˈɾa.xe]",translation:"гараж",example:"El coche está en el garaje.",exampleTranslation:"Машина в гараже."},
    {topic:"home",word:"escalera",transcription:"[es.kaˈle.ɾa]",translation:"лестница",example:"Subo por la escalera.",exampleTranslation:"Я поднимаюсь по лестнице."},
    {topic:"home",word:"ascensor",transcription:"[as.senˈsoɾ]",translation:"лифт",example:"Tomo el ascensor.",exampleTranslation:"Я еду на лифте."},
    {topic:"home",word:"estante",transcription:"[esˈtan.te]",translation:"полка",example:"El libro está en el estante.",exampleTranslation:"Книга на полке."},
    {topic:"home",word:"reloj de pared",transcription:"[reˈlox ðe paˈɾeð]",translation:"настенные часы",example:"El reloj de pared marca las tres.",exampleTranslation:"Настенные часы показывают три часа."},
    {topic:"home",word:"jabón",transcription:"[xaˈβon]",translation:"мыло",example:"El jabón huele bien.",exampleTranslation:"Мыло приятно пахнет."},
    {topic:"home",word:"grifo",transcription:"[ˈɡɾi.fo]",translation:"кран",example:"Abro el grifo.",exampleTranslation:"Я открываю кран."},
    {topic:"home",word:"papelera",transcription:"[pa.peˈle.ɾa]",translation:"мусорное ведро",example:"Tiro esto a la papelera.",exampleTranslation:"Я выбрасываю это в мусорку."},

    // --- STREET (50) ---
    {topic:"street",word:"calle",transcription:"[ˈka.ʎe]",translation:"улица",example:"La calle es larga.",exampleTranslation:"Улица длинная."},
    {topic:"street",word:"ciudad",transcription:"[sjuˈðað]",translation:"город",example:"La ciudad es bonita.",exampleTranslation:"Город красивый."},
    {topic:"street",word:"coche",transcription:"[ˈko.tʃe]",translation:"машина",example:"El coche es rápido.",exampleTranslation:"Машина быстрая."},
    {topic:"street",word:"autobús",transcription:"[au̯.toˈβus]",translation:"автобус",example:"El autobús llega pronto.",exampleTranslation:"Автобус скоро приедет."},
    {topic:"street",word:"parada",transcription:"[paˈɾa.ða]",translation:"остановка",example:"Espero en la parada.",exampleTranslation:"Я жду на остановке."},
    {topic:"street",word:"semáforo",transcription:"[seˈma.fo.ɾo]",translation:"светофор",example:"El semáforo está en rojo.",exampleTranslation:"Светофор красный."},
    {topic:"street",word:"paso de peatones",transcription:"[ˈpa.so ðe pe.aˈto.nes]",translation:"пешеходный переход",example:"Cruzo por el paso de peatones.",exampleTranslation:"Я перехожу по пешеходному переходу."},
    {topic:"street",word:"acera",transcription:"[aˈse.ɾa]",translation:"тротуар",example:"Camino por la acera.",exampleTranslation:"Я иду по тротуару."},
    {topic:"street",word:"edificio",transcription:"[e.ðiˈfi.sjo]",translation:"здание",example:"El edificio es alto.",exampleTranslation:"Здание высокое."},
    {topic:"street",word:"tienda",transcription:"[ˈtjen.da]",translation:"магазин",example:"La tienda está abierta.",exampleTranslation:"Магазин открыт."},
    {topic:"street",word:"supermercado",transcription:"[su.peɾ.meɾˈka.ðo]",translation:"супермаркет",example:"Voy al supermercado.",exampleTranslation:"Я иду в супермаркет."},
    {topic:"street",word:"parque",transcription:"[ˈpaɾ.ke]",translation:"парк",example:"El parque está verde.",exampleTranslation:"Парк зелёный."},
    {topic:"street",word:"plaza",transcription:"[ˈpla.sa]",translation:"площадь",example:"La plaza está llena.",exampleTranslation:"Площадь полна людей."},
    {topic:"street",word:"banco",transcription:"[ˈbaŋ.ko]",translation:"скамейка / банк",example:"Me siento en el banco.",exampleTranslation:"Я сажусь на скамейку."},
    {topic:"street",word:"árbol",transcription:"[ˈaɾ.βol]",translation:"дерево",example:"El árbol es grande.",exampleTranslation:"Дерево большое."},
    {topic:"street",word:"flor",transcription:"[floɾ]",translation:"цветок",example:"La flor es bonita.",exampleTranslation:"Цветок красивый."},
    {topic:"street",word:"puente",transcription:"[ˈpwen.te]",translation:"мост",example:"Cruzo el puente.",exampleTranslation:"Я перехожу мост."},
    {topic:"street",word:"río",transcription:"[ˈri.o]",translation:"река",example:"El río es profundo.",exampleTranslation:"Река глубокая."},
    {topic:"street",word:"bicicleta",transcription:"[bi.siˈkle.ta]",translation:"велосипед",example:"Tengo una bicicleta.",exampleTranslation:"У меня есть велосипед."},
    {topic:"street",word:"moto",transcription:"[ˈmo.to]",translation:"мотоцикл",example:"La moto es roja.",exampleTranslation:"Мотоцикл красный."},
    {topic:"street",word:"taxi",transcription:"[ˈtak.si]",translation:"такси",example:"Llamo a un taxi.",exampleTranslation:"Я вызываю такси."},
    {topic:"street",word:"estación",transcription:"[es.taˈsjon]",translation:"станция / вокзал",example:"La estación está cerca.",exampleTranslation:"Станция близко."},
    {topic:"street",word:"metro",transcription:"[ˈme.tɾo]",translation:"метро",example:"Voy en metro.",exampleTranslation:"Я еду на метро."},
    {topic:"street",word:"farmacia",transcription:"[faɾˈma.sja]",translation:"аптека",example:"La farmacia está allí.",exampleTranslation:"Аптека вон там."},
    {topic:"street",word:"restaurante",transcription:"[res.tau̯ˈɾan.te]",translation:"ресторан",example:"El restaurante es bueno.",exampleTranslation:"Ресторан хороший."},
    {topic:"street",word:"cafetería",transcription:"[ka.fe.teˈɾi.a]",translation:"кафе",example:"Entro en la cafetería.",exampleTranslation:"Я захожу в кафе."},
    {topic:"street",word:"museo",transcription:"[muˈse.o]",translation:"музей",example:"El museo está cerrado.",exampleTranslation:"Музей закрыт."},
    {topic:"street",word:"cine",transcription:"[ˈsi.ne]",translation:"кинотеатр",example:"Voy al cine hoy.",exampleTranslation:"Я иду в кино сегодня."},
    {topic:"street",word:"teatro",transcription:"[teˈa.tɾo]",translation:"театр",example:"El teatro es viejo.",exampleTranslation:"Театр старый."},
    {topic:"street",word:"hospital",transcription:"[os.piˈtal]",translation:"больница",example:"El hospital está lejos.",exampleTranslation:"Больница далеко."},
    {topic:"street",word:"escuela",transcription:"[esˈkwe.la]",translation:"школа",example:"La escuela es grande.",exampleTranslation:"Школа большая."},
    {topic:"street",word:"iglesia",transcription:"[iˈɣle.sja]",translation:"церковь",example:"La iglesia es antigua.",exampleTranslation:"Церковь старинная."},
    {topic:"street",word:"hotel",transcription:"[oˈtel]",translation:"отель",example:"El hotel es caro.",exampleTranslation:"Отель дорогой."},
    {topic:"street",word:"policía",transcription:"[po.liˈsi.a]",translation:"полиция",example:"Veo a la policía.",exampleTranslation:"Я вижу полицию."},
    {topic:"street",word:"carretera",transcription:"[ka.reˈte.ɾa]",translation:"шоссе / дорога",example:"La carretera es ancha.",exampleTranslation:"Дорога широкая."},
    {topic:"street",word:"esquina",transcription:"[esˈki.na]",translation:"угол (улицы)",example:"Giro en la esquina.",exampleTranslation:"Я поворачиваю на углу."},
    {topic:"street",word:"farola",transcription:"[faˈɾo.la]",translation:"уличный фонарь",example:"La farola brilla.",exampleTranslation:"Фонарь светит."},
    {topic:"street",word:"fuente",transcription:"[ˈfwen.te]",translation:"фонтан",example:"La fuente tiene agua.",exampleTranslation:"В фонтане есть вода."},
    {topic:"street",word:"kiosco",transcription:"[ˈkjos.ko]",translation:"киоск",example:"Compro un periódico en el kiosco.",exampleTranslation:"Я покупаю газету в киоске."},
    {topic:"street",word:"monumento",transcription:"[mo.nuˈmen.to]",translation:"памятник",example:"El monumento es famoso.",exampleTranslation:"Памятник знаменит."},
    {topic:"street",word:"pasaje",transcription:"[paˈsa.xe]",translation:"проход / переулок",example:"El pasaje es estrecho.",exampleTranslation:"Переулок узкий."},
    {topic:"street",word:"tráfico",transcription:"[ˈtɾa.fi.ko]",translation:"транспортный поток / пробка",example:"Hay mucho tráfico.",exampleTranslation:"Здесь большое движение."},
    {topic:"street",word:"peatón",transcription:"[pe.aˈton]",translation:"пешеход",example:"El peatón camina lento.",exampleTranslation:"Пешеход идёт медленно."},
    {topic:"street",word:"barrio",transcription:"[ˈba.rjo]",translation:"район / квартал",example:"Mi barrio es tranquilo.",exampleTranslation:"Мой район спокойный."},
    {topic:"street",word:"mercado",transcription:"[meɾˈka.ðo]",translation:"рынок",example:"El mercado está lleno.",exampleTranslation:"Рынок полон людей."},
    {topic:"street",word:"estancamiento",transcription:"[es.taŋ.kaˈmjen.to]",translation:"затор / пробка",example:"El estancamiento es largo.",exampleTranslation:"Пробка длинная."},
    {topic:"street",word:"estacón",transcription:"[es.taˈkon]",translation:"парковочный столбик",example:"El estacón es de metal.",exampleTranslation:"Столбик металлический."},
    {topic:"street",word:"cartel",transcription:"[kaɾˈtel]",translation:"вывеска / плакат",example:"El cartel es grande.",exampleTranslation:"Вывеска большая."},
    {topic:"street",word:"pasarela",transcription:"[pa.saˈɾe.la]",translation:"пешеходный мостик",example:"Cruzo la pasarela.",exampleTranslation:"Я иду по пешеходному мостику."},
    {topic:"street",word:"Avenida",transcription:"[a.βeˈni.ða]",translation:"проспект",example:"La avenida es muy ancha.",exampleTranslation:"Проспект очень широкий."},

    // --- WORK (50) ---
    {topic:"work",word:"trabajo",transcription:"[tɾaˈβa.xo]",translation:"работа",example:"Me gusta mi trabajo.",exampleTranslation:"Мне нравится моя работа."},
    {topic:"work",word:"oficina",transcription:"[o.fiˈsi.na]",translation:"офис",example:"La oficina es moderna.",exampleTranslation:"Офис современный."},
    {topic:"work",word:"jefe",transcription:"[ˈxe.fe]",translation:"начальник",example:"El jefe es simpático.",exampleTranslation:"Начальник симпатичный."},
    {topic:"work",word:"empleado",transcription:"[em.pleˈa.ðo]",translation:"сотрудник",example:"El empleado trabaja mucho.",exampleTranslation:"Сотрудник много работает."},
    {topic:"work",word:"ordenador",transcription:"[oɾ.ðe.naˈðoɾ]",translation:"компьютер",example:"El ordenador es nuevo.",exampleTranslation:"Компьютер новый."},
    {topic:"work",word:"teléfono",transcription:"[teˈle.fo.no]",translation:"телефон",example:"El teléfono suena.",exampleTranslation:"Телефон звонит."},
    {topic:"work",word:"reunión",transcription:"[reu̯ˈnjon]",translation:"совещание",example:"Tengo una reunión.",exampleTranslation:"У меня встреча."},
    {topic:"work",word:"correo",transcription:"[koˈre.o]",translation:"почта / письмо",example:"Escribo un correo.",exampleTranslation:"Я пишу письмо."},
    {topic:"work",word:"documento",transcription:"[do.kuˈmen.to]",translation:"документ",example:"Leo el documento.",exampleTranslation:"Я читаю документ."},
    {topic:"work",word:"proyecto",transcription:"[pɾoˈjek.to]",translation:"проект",example:"El proyecto es importante.",exampleTranslation:"Проект важный."},
    {topic:"work",word:"salario",transcription:"[saˈla.ɾjo]",translation:"зарплата",example:"El salario es bueno.",exampleTranslation:"Зарплата хорошая."},
    {topic:"work",word:"empresa",transcription:"[emˈpɾe.sa]",translation:"компания / фирма",example:"La empresa es grande.",exampleTranslation:"Компания большая."},
    {topic:"work",word:"cliente",transcription:"[kljenˈte]",translation:"клиент",example:"Hablo con el cliente.",exampleTranslation:"Я говорю с клиентом."},
    {topic:"work",word:"contrato",transcription:"[konˈtɾa.to]",translation:"контракт",example:"Firmo el contrato.",exampleTranslation:"Я подписываю контракт."},
    {topic:"work",word:"bolígrafo",transcription:"[boˈli.ɣɾa.fo]",translation:"ручка",example:"Necesito un bolígrafo.",exampleTranslation:"Мне нужна ручка."},
    {topic:"work",word:"papel",transcription:"[paˈpel]",translation:"бумага",example:"El papel es blanco.",exampleTranslation:"Бумага белая."},
    {topic:"work",word:"cuaderno",transcription:"[kwaˈðeɾ.no]",translation:"тетрадь / блокнот",example:"Escribo en el cuaderno.",exampleTranslation:"Я пишу в тетради."},
    {topic:"work",word:"tarea",transcription:"[taˈɾe.a]",translation:"задача / задание",example:"La tarea es fácil.",exampleTranslation:"Задание лёгкое."},
    {topic:"work",word:"horario",transcription:"[oˈɾa.ɾjo]",translation:"расписание / график",example:"Mi horario es flexible.",exampleTranslation:"Мой график гибкий."},
    {topic:"work",word:"equipo",transcription:"[eˈki.po]",translation:"команда",example:"Mi equipo es genial.",exampleTranslation:"Моя команда классная."},
    {topic:"work",word:"éxito",transcription:"[ˈek.si.to]",translation:"успех",example:"Deseo mucho éxito.",exampleTranslation:"Желаю большого успеха."},
    {topic:"work",word:"negocio",transcription:"[neˈɣo.sjo]",translation:"бизнес / дело",example:"El negocio crece.",exampleTranslation:"Бизнес растёт."},
    {topic:"work",word:"médico",transcription:"[ˈme.ði.ko]",translation:"врач",example:"El médico es bueno.",exampleTranslation:"Врач хороший."},
    {topic:"work",word:"profesor",transcription:"[pɾo.feˈsoɾ]",translation:"учитель",example:"El profesor explica bien.",exampleTranslation:"Учитель объясняет хорошо."},
    {topic:"work",word:"ingeniero",transcription:"[in.xeˈnje.ɾo]",translation:"инженер",example:"Soy ingeniero.",exampleTranslation:"Я инженер."},
    {topic:"work",word:"abogado",transcription:"[a.βoˈɣa.ðo]",translation:"адвокат / юрист",example:"El abogado ayuda.",exampleTranslation:"Адвокат помогает."},
    {topic:"work",word:"camarero",transcription:"[ka.maˈɾe.ɾo]",translation:"официант",example:"El camarero trae el café.",exampleTranslation:"Официант несёт кофе."},
    {topic:"work",word:"conductor",transcription:"[kon.dukˈtoɾ]",translation:"водитель",example:"El conductor conduce bien.",exampleTranslation:"Водитель хорошо водит."},
    {topic:"work",word:"secretario",transcription:"[se.kɾeˈta.ɾjo]",translation:"секретарь",example:"El secretario llama por teléfono.",exampleTranslation:"Секретарь звонит по телефону."},
    {topic:"work",word:"vendedor",transcription:"[ben.deˈðoɾ]",translation:"продавец",example:"El vendedor es amable.",exampleTranslation:"Продавец вежливый."},
    {topic:"work",word:"impresora",transcription:"[im.pɾeˈso.ɾa]",translation:"принтер",example:"La impresora no tiene papel.",exampleTranslation:"В принтере нет бумаги."},
    {topic:"work",word:"pantalla",transcription:"[panˈta.ʎa]",translation:"экран",example:"Miro la pantalla.",exampleTranslation:"Я смотрю на экран."},
    {topic:"work",word:"teclado",transcription:"[teˈkla.ðo]",translation:"клавиатура",example:"Escribo con el teclado.",exampleTranslation:"Я пишу на клавиатуре."},
    {topic:"work",word:"ratón",transcription:"[raˈton]",translation:"компьютерная мышь",example:"El ratón es negro.",exampleTranslation:"Мышка чёрная."},
    {topic:"work",word:"carpeta",transcription:"[kaɾˈpe.ta]",translation:"папка",example:"Guardo esto en la carpeta.",exampleTranslation:"Я сохраняю это в папку."},
    {topic:"work",word:"entrevista",transcription:"[en.tɾeˈβis.ta]",translation:"интервью / собеседование",example:"Tengo una entrevista hoy.",exampleTranslation:"У меня сегодня собеседование."},
    {topic:"work",word:"mensaje",transcription:"[menˈsa.xe]",translation:"сообщение",example:"Recibo un mensaje.",exampleTranslation:"Я получаю сообщение."},
    {topic:"work",word:"llamada",transcription:"[ʎaˈma.ða]",translation:"звонок",example:"Tengo una llamada.",exampleTranslation:"У меня звонок."},
    {topic:"work",word:"vacaciones",transcription:"[ba.kaˈsjo.nes]",translation:"отпуск",example:"Necesito vacaciones.",exampleTranslation:"Мне нужен отпуск."},
    {topic:"work",word:"descanso",transcription:"[desˈkan.so]",translation:"перерыв / отдых",example:"Tomo un descanso.",exampleTranslation:"Я беру перерыв."},
    {topic:"work",word:"firma",transcription:"[ˈfiɾ.ma]",translation:"подпись",example:"Necesito su firma.",exampleTranslation:"Мне нужна ваша подпись."},
    {topic:"work",word:"fichero",transcription:"[fiˈtʃe.ɾo]",translation:"файл / картотека",example:"El fichero está listo.",exampleTranslation:"Файл готов."},
    {topic:"work",word:"agenda",transcription:"[aˈxen.da]",translation:"записная книжка",example:"Apunto todo en mi agenda.",exampleTranslation:"Я записываю всё в блокнот."},
    {topic:"work",word:"informe",transcription:"[inˈfoɾ.me]",translation:"отчёт",example:"Leo el informe.",exampleTranslation:"Я читаю отчёт."},
    {topic:"work",word:"calculadora",transcription:"[kal.ku.laˈðo.ɾa]",translation:"калькулятор",example:"Uso la calculadora.",exampleTranslation:"Я использую калькулятор."},
    {topic:"work",word:"sello",transcription:"[ˈse.ʎo]",translation:"печать / штамп",example:"Pongo el sello.",exampleTranslation:"Я ставлю печать."},
    {topic:"work",word:"escritorio",transcription:"[es.kɾiˈto.ɾjo]",translation:"письменный стол",example:"Mi escritorio está limpio.",exampleTranslation:"Мой стол чистый."},
    {topic:"work",word:"compañero",transcription:"[kom.paˈɲe.ɾo]",translation:"коллега",example:"Mi compañero me ayuda.",exampleTranslation:"Мой коллега помогает мне."},
    {topic:"work",word:"puesto",transcription:"[ˈpwes.to]",translation:"должность / рабочее место",example:"Busco un nuevo puesto.",exampleTranslation:"Я ищу новую должность."},
    {topic:"work",word:"reunión virtual",transcription:"[reu̯ˈnjon biɾˈtwal]",translation:"онлайн-встреча",example:"Tengo una reunión virtual.",exampleTranslation:"У меня онлайн-встреча."},

    // --- TRAVEL (50) ---
    {topic:"travel",word:"viaje",transcription:"[ˈbja.xe]",translation:"путешествие",example:"El viaje es largo.",exampleTranslation:"Путешествие длинное."},
    {topic:"travel",word:"maleta",transcription:"[maˈle.ta]",translation:"чемодан",example:"La maleta es pesada.",exampleTranslation:"Чемодан тяжёлый."},
    {topic:"travel",word:"pasaporte",transcription:"[pa.saˈpoɾ.te]",translation:"паспорт",example:"Tengo el pasaporte.",exampleTranslation:"У меня есть паспорт."},
    {topic:"travel",word:"billete",transcription:"[biˈʎe.te]",translation:"билет",example:"Compro un billete.",exampleTranslation:"Я покупаю билет."},
    {topic:"travel",word:"avión",transcription:"[aˈβjon]",translation:"самолёт",example:"El avión vuela alto.",exampleTranslation:"Самолёт летит высоко."},
    {topic:"travel",word:"aeropuerto",transcription:"[a.e.ɾoˈpweɾ.to]",translation:"аэропорт",example:"El aeropuerto es enorme.",exampleTranslation:"Аэропорт огромный."},
    {topic:"travel",word:"tren",transcription:"[tɾen]",translation:"поезд",example:"El tren sale ahora.",exampleTranslation:"Поезд отправляется сейчас."},
    {topic:"travel",word:"mapa",transcription:"[ˈma.pa]",translation:"карта",example:"Miro el mapa.",exampleTranslation:"Я смотрю на карту."},
    {topic:"travel",word:"turista",transcription:"[tuˈɾis.ta]",translation:"турист",example:"El turista saca fotos.",exampleTranslation:"Турист делает фото."},
    {topic:"travel",word:"playa",transcription:"[ˈpla.ja]",translation:"пляж",example:"La playa es hermosa.",exampleTranslation:"Пляж सुंदर."},
    {topic:"travel",word:"mar",transcription:"[maɾ]",translation:"море",example:"El mar está azul.",exampleTranslation:"Море синее."},
    {topic:"travel",word:"sol",transcription:"[sol]",translation:"солнце",example:"El sol brilla.",exampleTranslation:"Солнце светит."},
    {topic:"travel",word:"montaña",transcription:"[monˈta.ɲa]",translation:"гора",example:"La montaña es alta.",exampleTranslation:"Гора высокая."},
    {topic:"travel",word:"guía",transcription:"[ˈɡi.a]",translation:"гид / путеводитель",example:"El guía habla español.",exampleTranslation:"Гид говорит по-испански."},
    {topic:"travel",word:"excursión",transcription:"[eks.kuɾˈsjon]",translation:"экскурсия",example:"Voy de excursión.",exampleTranslation:"Я иду на экскурсию."},
    {topic:"travel",word:"reserva",transcription:"[reˈseɾ.βa]",translation:"бронь / резервация",example:"Tengo una reserva.",exampleTranslation:"У меня есть бронь."},
    {topic:"travel",word:"foto",transcription:"[ˈfo.to]",translation:"фотография",example:"Tomo una foto.",exampleTranslation:"Я делаю фотографию."},
    {topic:"travel",word:"cámara",transcription:"[ˈka.ma.ɾa]",translation:"камера / фотоаппарат",example:"La cámara es nueva.",exampleTranslation:"Камера новая."},
    {topic:"travel",word:"mochila",transcription:"[moˈtʃi.la]",translation:"рюкзак",example:"Llevo una mochila.",exampleTranslation:"Я несу рюкзак."},
    {topic:"travel",word:"país",transcription:"[paˈis]",translation:"страна",example:"Este país es lindo.",exampleTranslation:"Эта страна красивая."},
    {topic:"travel",word:"vuelo",transcription:"[ˈbwe.lo]",translation:"рейс / полёт",example:"El vuelo llega a tiempo.",exampleTranslation:"Рейс прибывает вовремя."},
    {topic:"travel",word:"equipaje",transcription:"[e.kiˈpa.xe]",translation:"багаж",example:"Busco mi equipaje.",exampleTranslation:"Я ищу свой багаж."},
    {topic:"travel",word:"aduana",transcription:"[aˈðwa.na]",translation:"таможня",example:"Paso por la aduana.",exampleTranslation:"Я прохожу таможню."},
    {topic:"travel",word:"vista",transcription:"[ˈbis.ta]",translation:"вид",example:"La vista es increíble.",exampleTranslation:"Вид невероятный."},
    {topic:"travel",word:"isla",transcription:"[ˈis.la]",translation:"остров",example:"La isla es pequeña.",exampleTranslation:"Остров маленький."},
    {topic:"travel",word:"barco",transcription:"[ˈbaɾ.ko]",translation:"корабль",example:"El barco navega.",exampleTranslation:"Корабль плывёт."},
    {topic:"travel",word:"ruta",transcription:"[ˈru.ta]",translation:"маршрут",example:"Sigo la ruta.",exampleTranslation:"Я следую маршруту."},
    {topic:"travel",word:"souvenir",transcription:"[su.βeˈniɾ]",translation:"сувенир",example:"Compro un souvenir.",exampleTranslation:"Я покупаю сувенир."},
    {topic:"travel",word:"recepción",transcription:"[re.sepˈsjon]",translation:"стойка регистрации",example:"Voy a la recepción.",exampleTranslation:"Я иду на стойку регистрации."},
    {topic:"travel",word:"llave del hotel",transcription:"[ˈʎa.βe ðel oˈtel]",translation:"ключ от номера",example:"Pido la llave del hotel.",exampleTranslation:"Я прошу ключ от номера."},
    {topic:"travel",word:"camino",transcription:"[kaˈmi.no]",translation:"тропа / путь",example:"El camino es largo.",exampleTranslation:"Путь длинный."},
    {topic:"travel",word:"destino",transcription:"[desˈti.no]",translation:"пункт назначения",example:"El destino está cerca.",exampleTranslation:"Пункт назначения близко."},
    {topic:"travel",word:"aventura",transcription:"[a.βenˈtu.ɾa]",translation:"приключение",example:"Es una gran aventura.",exampleTranslation:"Это большое приключение."},
    {topic:"travel",word:"campamento",transcription:"[kam.paˈmen.to]",translation:"кемпинг / лагерь",example:"Dormimos en el campamento.",exampleTranslation:"Мы спим в лагере."},
    {topic:"travel",word:"tienda de campaña",transcription:"[ˈtjen.da ðe kamˈpa.ɲa]",translation:"палатка",example:"La tienda de campaña es roja.",exampleTranslation:"Палатка красная."},
    {topic:"travel",word:"lago",transcription:"[ˈla.ɣo]",translation:"озеро",example:"El lago es tranquilo.",exampleTranslation:"Озеро спокойное."},
    {topic:"travel",word:"bosque",transcription:"[ˈbos.ke]",translation:"лес",example:"Camino por el bosque.",exampleTranslation:"Я иду по лесу."},
    {topic:"travel",word:"arena",transcription:"[aˈɾe.na]",translation:"песок",example:"La arena está caliente.",exampleTranslation:"Песок горячий."},
    {topic:"travel",word:"ola",transcription:"[ˈo.la]",translation:"волна",example:"La ola es grande.",exampleTranslation:"Волна большая."},
    {topic:"travel",word:"crucero",transcription:"[kɾuˈse.ɾo]",translation:"круиз",example:"El crucero es enorme.",exampleTranslation:"Круизный лайнер огромный."},
    {topic:"travel",word:"moneda",transcription:"[moˈne.ða]",translation:"монета / валюта",example:"Cambio moneda.",exampleTranslation:"Я меняю валюту."},
    {topic:"travel",word:"cambio",transcription:"[ˈkam.bjo]",translation:"обмен валюты",example:"¿Dónde está el cambio?",exampleTranslation:"Где обмен валюты?"},
    {topic:"travel",word:"tarjeta de embarque",transcription:"[taɾˈxe.ta ðe emˈbaɾ.ke]",translation:"посадочный талон",example:"Tengo la tarjeta de embarque.",exampleTranslation:"У меня есть посадочный талон."},
    {topic:"travel",word:"equipaje de mano",transcription:"[e.kiˈpa.xe ðe ˈma.no]",translation:"ручная кладь",example:"Llevo equipaje de mano.",exampleTranslation:"У меня ручная кладь."},
    {topic:"travel",word:"vuelo directo",transcription:"[ˈbwe.lo diˈɾek.to]",translation:"прямой рейс",example:"Es un vuelo directo.",exampleTranslation:"Это прямой рейс."},
    {topic:"travel",word:"paisaje",transcription:"[pai̯ˈsa.xe]",translation:"пейзаж",example:"El paisaje es hermoso.",exampleTranslation:"Пейзаж красивый."},
    {topic:"travel",word:"excursión en barco",transcription:"[eks.kuɾˈsjon en ˈbaɾ.ko]",translation:"прогулка на катере",example:"Hacemos una excursión en barco.",exampleTranslation:"У нас прогулка на катере."},
    {topic:"travel",word:"monumento histórico",transcription:"[mo.nuˈmen.to isˈto.ɾi.ko]",translation:"исторический памятник",example:"Es un monumento histórico.",exampleTranslation:"Это исторический памятник."},
    {topic:"travel",word:"seguro de viaje",transcription:"[seˈɣu.ɾo ðe ˈbja.xe]",translation:"страховка для путешествия",example:"Tengo seguro de viaje.",exampleTranslation:"У меня есть страховка."},
    {topic:"travel",word:"frontera",transcription:"[fɾonˈte.ɾa]",translation:"граница",example:"Cruzamos la frontera.",exampleTranslation:"Мы пересекаем границу."},

    // --- FEELINGS (50) ---
    {topic:"feelings",word:"feliz",transcription:"[feˈlis]",translation:"счастливый",example:"Estoy muy feliz.",exampleTranslation:"Я очень счастлив."},
    {topic:"feelings",word:"triste",transcription:"[ˈtɾis.te]",translation:"грустный",example:"El niño está triste.",exampleTranslation:"Мальчик грустный."},
    {topic:"feelings",word:"cansado",transcription:"[kanˈsa.ðo]",translation:"уставший",example:"Estoy cansado hoy.",exampleTranslation:"Я устал сегодня."},
    {topic:"feelings",word:"enfadado",transcription:"[em.faˈða.ðo]",translation:"злой / сердитый",example:"Mi amigo está enfadado.",exampleTranslation:"Мой друг сердит."},
    {topic:"feelings",word:"asustado",transcription:"[a.susˈta.ðo]",translation:"испуганный",example:"El gato está asustado.",exampleTranslation:"Кот испуган."},
    {topic:"feelings",word:"sorprendido",transcription:"[soɾ.pɾenˈdi.ðo]",translation:"удивлённый",example:"Estoy sorprendido.",exampleTranslation:"Я удивлён."},
    {topic:"feelings",word:"tranquilo",transcription:"[tɾaŋˈki.lo]",translation:"спокойный",example:"El lugar es tranquilo.",exampleTranslation:"Место спокойное."},
    {topic:"feelings",word:"nervioso",transcription:"[neɾˈβjo.so]",translation:"нервный",example:"Estoy nervioso por el examen.",exampleTranslation:"Я нервничаю из-за экзамена."},
    {topic:"feelings",word:"contento",transcription:"[konˈten.to]",translation:"довольный",example:"Estoy contento con mi trabajo.",exampleTranslation:"Я доволен своей работой."},
    {topic:"feelings",word:"aburrido",transcription:"[a.βuˈri.ðo]",translation:"скучающий / скучный",example:"La película es aburrida.",exampleTranslation:"Фильм скучный."},
    {topic:"feelings",word:"amor",transcription:"[aˈmoɾ]",translation:"любовь",example:"Siento mucho amor.",exampleTranslation:"Я чувствую большую любовь."},
    {topic:"feelings",word:"odio",transcription:"[ˈo.ðjo]",translation:"ненависть",example:"No me gusta el odio.",exampleTranslation:"Мне не нравится ненависть."},
    {topic:"feelings",word:"miedo",transcription:"[ˈmje.ðo]",translation:"страх",example:"Tengo miedo.",exampleTranslation:"Мне страшно."},
    {topic:"feelings",word:"alegría",transcription:"[a.leˈɣɾi.a]",translation:"радость",example:"Siento alegría.",exampleTranslation:"Я чувствую радость."},
    {topic:"feelings",word:"dolor",transcription:"[doˈloɾ]",translation:"боль",example:"Tengo un dolor fuerte.",exampleTranslation:"У меня сильная боль."},
    {topic:"feelings",word:"paz",transcription:"[pas]",translation:"мир / покой",example:"Quiero paz.",exampleTranslation:"Я хочу покоя."},
    {topic:"feelings",word:"esperanza",transcription:"[es.peˈɾan.sa]",translation:"надежда",example:"Tengo esperanza.",exampleTranslation:"У меня есть надежда."},
    {topic:"feelings",word:"orgullo",transcription:"[oɾˈɡu.ʎo]",translation:"гордость",example:"Siento orgullo de ti.",exampleTranslation:"Я горжусь тобой."},
    {topic:"feelings",word:"vergüenza",transcription:"[beɾˈɡwen.sa]",translation:"стыд",example:"Siento vergüenza.",exampleTranslation:"Мне стыдно."},
    {topic:"feelings",word:"envidia",transcription:"[emˈbi.ðja]",translation:"зависть",example:"La envidia es mala.",exampleTranslation:"Зависть — это плохо."},
    {topic:"feelings",word:"celos",transcription:"[ˈse.los]",translation:"ревность",example:"Tengo celos.",exampleTranslation:"Я ревную."},
    {topic:"feelings",word:"calma",transcription:"[ˈkal.ma]",translation:"спокойствие / тишина",example:"Mantengo la calma.",exampleTranslation:"Я сохраняю спокойствие."},
    {topic:"feelings",word:"ansiedad",transcription:"[an.sjeˈðað]",translation:"тревожность",example:"Siento ansiedad.",exampleTranslation:"Я чувствую тревогу."},
    {topic:"feelings",word:"estrés",transcription:"[esˈtɾes]",translation:"стресс",example:"Tengo mucho estrés.",exampleTranslation:"У меня большой стресс."},
    {topic:"feelings",word:"empatía",transcription:"[em.paˈti.a]",translation:"эмпатия",example:"Tengo empatía.",exampleTranslation:"Я сопереживаю."},
    {topic:"feelings",word:"ilusión",transcription:"[i.luˈsjon]",translation:"воодушевление / вдохновение",example:"Tengo mucha ilusión.",exampleTranslation:"Я полон вдохновения."},
    {topic:"feelings",word:"soledad",transcription:"[so.leˈðað]",translation:"одиночество",example:"Siento soledad.",exampleTranslation:"Я чувствую одиночество."},
    {topic:"feelings",word:"nostalgia",transcription:"[nosˈtal.xja]",translation:"ностальгия",example:"Tengo nostalgia.",exampleTranslation:"У меня ностальгия."},
    {topic:"feelings",word:"simpatía",transcription:"[sim.paˈti.a]",translation:"симпатия",example:"Siento simpatía por él.",exampleTranslation:"Я чувствую симпатию к нему."},
    {topic:"feelings",word:"confianza",transcription:"[komˈfjan.sa]",translation:"доверие / уверенность",example:"Tengo confianza.",exampleTranslation:"У меня есть уверенность."},
    {topic:"feelings",word:"duda",transcription:"[ˈdu.ða]",translation:"сомнение",example:"Tengo una duda.",exampleTranslation:"У меня есть сомнение."},
    {topic:"feelings",word:"curiosidad",transcription:"[ku.ɾjo.siˈðað]",translation:"любопытство",example:"Tengo curiosidad.",exampleTranslation:"Мне любопытно."},
    {topic:"feelings",word:"paciencia",transcription:"[paˈsjen.sja]",translation:"терпение",example:"Tengo paciencia.",exampleTranslation:"У меня есть терпение."},
    {topic:"feelings",word:"culpa",transcription:"[ˈkul.pa]",translation:"вина",example:"Siento culpa.",exampleTranslation:"Я чувствую вину."},
    {topic:"feelings",word:"alivio",transcription:"[aˈli.βjo]",translation:"облегчение",example:"Qué alivio.",exampleTranslation:"Какое облегчение."},
    {topic:"feelings",word:"cariño",transcription:"[kaˈɾi.ɲo]",translation:"нежность / ласка",example:"Le tengo mucho cariño.",exampleTranslation:"Я отношусь к нему с большой нежностью."},
    {topic:"feelings",word:"rabia",transcription:"[ˈra.βja]",translation:"ярость / гнева",example:"Siento rabia.",exampleTranslation:"Я чувствую ярость."},
    {topic:"feelings",word:"gratitud",transcription:"[ɡɾa.tiˈtuð]",translation:"благодарность",example:"Siento gratitud.",exampleTranslation:"Я чувствую благодарность."},
    {topic:"feelings",word:"ilusión óptica",transcription:"[i.luˈsjon ˈop.ti.ka]",translation:"обман / иллюзия",example:"Es una ilusión.",exampleTranslation:"Это иллюзия."},
    {topic:"feelings",word:"entusiasmo",transcription:"[en.tuˈsjas.mo]",translation:"энтузиазм",example:"Tengo entusiasmo.",exampleTranslation:"У меня есть энтузиазм."},
    {topic:"feelings",word:"decepción",transcription:"[de.sepˈsjon]",translation:"разочарование",example:"Es una decepción.",exampleTranslation:"Это разочарование."},
    {topic:"feelings",word:"pasión",transcription:"[paˈsjon]",translation:"страсть",example:"Siento pasión.",exampleTranslation:"Я чувствую страсть."},
    {topic:"feelings",word:"seguridad",transcription:"[se.ɣu.ɾiˈðað]",translation:"уверенность",example:"Tengo seguridad.",exampleTranslation:"Я уверен в себе."},
    {topic:"feelings",word:"angustia",transcription:"[aŋˈgus.tja]",translation:"тревога / тоска",example:"Siento angustia.",exampleTranslation:"Я чувствую тоску."},
    {topic:"feelings",word:"asombro",transcription:"[aˈsom.bɾo]",translation:"изумление",example:"Qué asombro.",exampleTranslation:"Какое изумление."},
    {topic:"feelings",word:"afecto",transcription:"[aˈfek.to]",translation:"привязанность",example:"Siento afecto.",exampleTranslation:"Я чувствую привязанность."},
    {topic:"feelings",word:"asco",transcription:"[ˈas.ko]",translation:"отвращение",example:"Me da asco.",exampleTranslation:"Мне это противно."},
    {topic:"feelings",word:"compasión",transcription:"[kom.paˈsjon]",translation:"сострадание",example:"Siento compasión.",exampleTranslation:"Я чувствую сострадание."},
    {topic:"feelings",word:"melancolía",transcription:"[me.laŋ.koˈli.a]",translation:"меланхолия",example:"Tengo melancolía.",exampleTranslation:"У меня меланхолия."},
    {topic:"feelings",word:"satisfacción",transcription:"[sa.tis.fakˈsjon]",translation:"удовлетворение",example:"Siento satisfacción.",exampleTranslation:"Я чувствую удовлетворение."},

    // --- ANIMALS (50) ---
    {topic:"animals",word:"perro",transcription:"[ˈpe.ro]",translation:"собака",example:"El perro ladra.",exampleTranslation:"Собака лает."},
    {topic:"animals",word:"gato",transcription:"[ˈɡa.to]",translation:"кот / кошка",example:"El gato duerme.",exampleTranslation:"Кот спит."},
    {topic:"animals",word:"pájaro",transcription:"[ˈpa.xa.ɾo]",translation:"птица",example:"El pájaro canta.",exampleTranslation:"Птица поёт."},
    {topic:"animals",word:"caballo",transcription:"[kaˈβa.ʎo]",translation:"лошадь",example:"El caballo corre.",exampleTranslation:"Лошадь бежит."},
    {topic:"animals",word:"vaca",transcription:"[ˈba.ka]",translation:"корова",example:"La vaca da leche.",exampleTranslation:"Корова даёт молоко."},
    {topic:"animals",word:"oveja",transcription:"[oˈβe.xa]",translation:"овца",example:"La oveja es blanca.",exampleTranslation:"Овца белая."},
    {topic:"animals",word:"cerdo",transcription:"[ˈseɾ.ðo]",translation:"свинья",example:"El cerdo es rosa.",exampleTranslation:"Свинья розовая."},
    {topic:"animals",word:"ratón de campo",transcription:"[raˈton de ˈkam.po]",translation:"мышь",example:"El ratón es pequeño.",exampleTranslation:"Мышь маленькая."},
    {topic:"animals",word:"león",transcription:"[leˈon]",translation:"лев",example:"El león es fuerte.",exampleTranslation:"Лев сильный."},
    {topic:"animals",word:"tigre",transcription:"[ˈti.ɣɾe]",translation:"тигр",example:"El tigre es rápido.",exampleTranslation:"Тигр быстрый."},
    {topic:"animals",word:"elefante",transcription:"[e.leˈfan.te]",translation:"слон",example:"El elefante es grande.",exampleTranslation:"Слон большой."},
    {topic:"animals",word:"oso",transcription:"[ˈo.so]",translation:"медведь",example:"El oso duerme en invierno.",exampleTranslation:"Медведь спит зимой."},
    {topic:"animals",word:"mono",transcription:"[ˈmo.no]",translation:"обезьяна",example:"El mono come un plátano.",exampleTranslation:"Обезьяна ест банан."},
    {topic:"animals",word:"pato",transcription:"[ˈpa.to]",translation:"утка",example:"El pato nada.",exampleTranslation:"Утка плавает."},
    {topic:"animals",word:"gallina",transcription:"[ɡaˈʎi.na]",translation:"курица (птица)",example:"La gallina pone huevos.",exampleTranslation:"Курица несёт яйца."},
    {topic:"animals",word:"gallo",transcription:"[ˈɡa.ʎo]",translation:"петух",example:"El gallo canta temprano.",exampleTranslation:"Петух поёт рано."},
    {topic:"animals",word:"serpiente",transcription:"[seɾˈpjen.te]",translation:"змея",example:"La serpiente es larga.",exampleTranslation:"Змея длинная."},
    {topic:"animals",word:"conejo",transcription:"[koˈne.xo]",translation:"кролик",example:"El conejo salta.",exampleTranslation:"Кролик прыгает."},
    {topic:"animals",word:"lobo",transcription:"[ˈlo.βo]",translation:"волк",example:"El lobo aúlla.",exampleTranslation:"Волк воет."},
    {topic:"animals",word:"zorro",transcription:"[ˈso.ro]",translation:"лиса",example:"El zorro es listo.",exampleTranslation:"Лиса умная."},
    {topic:"animals",word:"jirafa",transcription:"[xiˈɾa.fa]",translation:"жираф",example:"La jirafa tiene el cuello alto.",exampleTranslation:"У жирафа высокая шея."},
    {topic:"animals",word:"cebra",transcription:"[ˈse.βɾa]",translation:"зебра",example:"La cebra tiene rayas.",exampleTranslation:"Зебра полосатая."},
    {topic:"animals",word:"hipopótamo",transcription:"[i.poˈpo.ta.mo]",translation:"гиппопотам",example:"El hipopótamo está en el agua.",exampleTranslation:"Бегемот в воде."},
    {topic:"animals",word:"cocodrilo",transcription:"[ko.koˈðɾi.lo]",translation:"крокодил",example:"El cocodrilo es peligroso.",exampleTranslation:"Крокодил опасный."},
    {topic:"animals",word:"delfín",transcription:"[delˈfin]",translation:"дельфин",example:"El delfín salta alto.",exampleTranslation:"Дельфин высоко прыгает."},
    {topic:"animals",word:"ballena",transcription:"[baˈʎe.na]",translation:"кит",example:"La ballena es enorme.",exampleTranslation:"Кит огромный."},
    {topic:"animals",word:"tiburón",transcription:"[ti.βuˈɾon]",translation:"акула",example:"El tiburón nada rápido.",exampleTranslation:"Акула быстро плавает."},
    {topic:"animals",word:"águila",transcription:"[ˈa.ɣi.la]",translation:"орёл",example:"El águila vuela alto.",exampleTranslation:"Орёл летит высоко."},
    {topic:"animals",word:"búho",transcription:"[ˈbu.o]",translation:"сова",example:"El búho mira por la noche.",exampleTranslation:"Сова смотрит ночью."},
    {topic:"animals",word:"mariposa",transcription:"[ma.ɾiˈpo.sa]",translation:"бабочка",example:"La mariposa es bonita.",exampleTranslation:"Бабочка красивая."},
    {topic:"animals",word:"abeja",transcription:"[aˈβe.xa]",translation:"пчела",example:"La abeja hace miel.",exampleTranslation:"Пчела делает мёд."},
    {topic:"animals",word:"hormiga",transcription:"[oɾˈmi.ɣa]",translation:"муравей",example:"La hormiga trabaja mucho.",exampleTranslation:"Муравей много работает."},
    {topic:"animals",word:"araña",transcription:"[aˈɾa.ɲa]",translation:"паук",example:"La araña hace una red.",exampleTranslation:"Паук плетет паутину."},
    {topic:"animals",word:"rana",transcription:"[ˈra.na]",translation:"лягушка",example:"La rana salta al agua.",exampleTranslation:"Лягушка прыгает в воду."},
    {topic:"animals",word:"tortuga",transcription:"[toɾˈtu.ɣa]",translation:"черепаха",example:"La tortuga camina lento.",exampleTranslation:"Черепаха идет медленно."},
    {topic:"animals",word:"camello",transcription:"[kaˈme.ʎo]",translation:"верблюд",example:"El camello vive en el desierto.",exampleTranslation:"Верблюд живёт в пустыне."},
    {topic:"animals",word:"ardilla",transcription:"[aɾˈði.ʎa]",translation:"белка",example:"La ardilla come nueces.",exampleTranslation:"Белка ест орехи."},
    {topic:"animals",word:"ciervo",transcription:"[ˈsjeɾ.βo]",translation:"олень",example:"El ciervo vive en el bosque.",exampleTranslation:"Олень живёт в лесу."},
    {topic:"animals",word:"pingüino",transcription:"[piŋˈɡwi.no]",translation:"пингвин",example:"El pingüino vive en el frío.",exampleTranslation:"Пингвин живёт в холоде."},
    {topic:"animals",word:"canguro",transcription:"[kaŋˈɡu.ɾo]",translation:"кенгуру",example:"El canguro salta mucho.",exampleTranslation:"Кенгуру много прыгает."},
    {topic:"animals",word:"p Panda",transcription:"[ˈpan.da]",translation:"панда",example:"El panda come bambú.",exampleTranslation:"Панда ест бамбук."},
    {topic:"animals",word:"flamenco",transcription:"[flaˈmeŋ.ko]",translation:"фламинго",example:"El flamenco es rosa.",exampleTranslation:"Фламинго розовый."},
    {topic:"animals",word:"pulpo",transcription:"[ˈpul.po]",translation:"осьминог",example:"El pulpo tiene ocho brazos.",exampleTranslation:"У осьминога восемь ног."},
    {topic:"animals",word:"cangrejo",transcription:"[kaŋˈɡɾe.xo]",translation:"краб",example:"El cangrejo camina de lado.",exampleTranslation:"Краб ходит боком."},
    {topic:"animals",word:"murciélago",transcription:"[muɾˈsje.la.ɣo]",translation:"летучая мышь",example:"El murciélago vuela de noche.",exampleTranslation:"Летучая мышь летает ночью."},
    {topic:"animals",word:"mula",transcription:"[ˈmu.la]",translation:"мул",example:"La mula es fuerte.",exampleTranslation:"Мул сильный."},
    {topic:"animals",word:"burro",transcription:"[ˈbu.ro]",translation:"осёл",example:"El burro camina despacio.",exampleTranslation:"Осёл идёт медленно."},
    {topic:"animals",word:"pavo",transcription:"[ˈpa.βo]",translation:"индейка / индюк",example:"El pavo es grande.",exampleTranslation:"Индюк большой."},
    {topic:"animals",word:"mosquito",transcription:"[mosˈki.to]",translation:"комар",example:"El mosquito molesta.",exampleTranslation:"Комар мешает."},
    {topic:"animals",word:"mosca",transcription:"[ˈmos.ka]",translation:"муха",example:"La mosca vuela rápido.",exampleTranslation:"Муха летает быстро."},

    // --- BODY (50) ---
    {topic:"body",word:"cabeza",transcription:"[kaˈβe.sa]",translation:"голова",example:"Me duele la cabeza.",exampleTranslation:"У меня болит голова."},
    {topic:"body",word:"ojo",transcription:"[ˈo.xo]",translation:"глаз",example:"Tengo los ojos azules.",exampleTranslation:"У меня голубые глаза."},
    {topic:"body",word:"nariz",transcription:"[naˈɾis]",translation:"нос",example:"La nariz está roja.",exampleTranslation:"Нос красный."},
    {topic:"body",word:"boca",transcription:"[ˈbo.ka]",translation:"рот",example:"Abre la boca.",exampleTranslation:"Открой рот."},
    {topic:"body",word:"oreja",transcription:"[oˈɾe.xa]",translation:"ухо (раковина)",example:"Tengo dos orejas.",exampleTranslation:"У меня два уха."},
    {topic:"body",word:"pelo",transcription:"[ˈpe.lo]",translation:"волосы",example:"Mi pelo es negro.",exampleTranslation:"Мои волосы чёрные."},
    {topic:"body",word:"cara",transcription:"[ˈka.ɾa]",translation:"лицо",example:"Lavo mi cara.",exampleTranslation:"Я умываю лицо."},
    {topic:"body",word:"mano",transcription:"[ˈma.no]",translation:"рука (кисть)",example:"Tengo agua en la mano.",exampleTranslation:"У меня вода в руке."},
    {topic:"body",word:"brazo",transcription:"[ˈbɾa.so]",translation:"рука (вся)",example:"El brazo me duele.",exampleTranslation:"У меня болит рука."},
    {topic:"body",word:"pierna",transcription:"[ˈpjeɾ.na]",translation:"нога (вся)",example:"La pierna es larga.",exampleTranslation:"Нога длинная."},
    {topic:"body",word:"pie",transcription:"[pje]",translation:"нога (стопа)",example:"Me duele el pie.",exampleTranslation:"У меня болит стопа."},
    {topic:"body",word:"dedo",transcription:"[ˈde.ðo]",translation:"палец",example:"Tengo cinco dedos.",exampleTranslation:"У меня пять пальцев."},
    {topic:"body",word:"espalda",transcription:"[esˈpal.da]",translation:"спина",example:"La espalda me duele.",exampleTranslation:"Спина болит."},
    {topic:"body",word:"estómago",transcription:"[esˈto.ma.ɣo]",translation:"живот / желудок",example:"El estómago está lleno.",exampleTranslation:"Живот полный."},
    {topic:"body",word:"corazón",transcription:"[ko.ɾaˈson]",translation:"сердце",example:"El corazón late.",exampleTranslation:"Сердце бьётся."},
    {topic:"body",word:"sangre",transcription:"[ˈsaŋ.ɡɾe]",translation:"кровы",example:"La sangre es roja.",exampleTranslation:"Кровь красная."},
    {topic:"body",word:"hueso",transcription:"[ˈwe.so]",translation:"кость",example:"El hueso es duro.",exampleTranslation:"Кость твёрдая."},
    {topic:"body",word:"piel",transcription:"[pjel]",translation:"кожа",example:"La piel es suave.",exampleTranslation:"Кожа мягкая."},
    {topic:"body",word:"diente",transcription:"[ˈdjen.te]",translation:"зуб",example:"Lavo los dientes.",exampleTranslation:"Я чищу зубы."},
    {topic:"body",word:"lengua",transcription:"[ˈleŋ.gwa]",translation:"язык",example:"La lengua es rosa.",exampleTranslation:"Язык розовый."},
    {topic:"body",word:"cuello",transcription:"[ˈkwe.ʎo]",translation:"шея",example:"El cuello me duele.",exampleTranslation:"Шея болит."},
    {topic:"body",word:"hombro",transcription:"[ˈom.bɾo]",translation:"плечо",example:"Tengo dolor en el hombro.",exampleTranslation:"У меня боль в плече."},
    {topic:"body",word:"codo",transcription:"[ˈko.ðo]",translation:"локоть",example:"El codo está roto.",exampleTranslation:"Локоть сломан."},
    {topic:"body",word:"rodilla",transcription:"[roˈði.ʎa]",translation:"колено",example:"La rodilla me duele.",exampleTranslation:"Колено болит."},
    {topic:"body",word:"tobillo",transcription:"[toˈβi.ʎo]",translation:"лодыжка",example:"El tobillo está hinchado.",exampleTranslation:"Лодыжка опухла."},
    {topic:"body",word:"pecho",transcription:"[ˈpe.tʃo]",translation:"грудь",example:"Me duele el pecho.",exampleTranslation:"У меня болит грудь."},
    {topic:"body",word:"uña",transcription:"[ˈu.ɲa]",translation:"ноготь",example:"La uña es larga.",exampleTranslation:"Ноготь длинный."},
    {topic:"body",word:"labio",transcription:"[ˈla.βjo]",translation:"губа",example:"Los labios están secos.",exampleTranslation:"Губы сухие."},
    {topic:"body",word:"garganta",transcription:"[ɡaɾˈɡan.ta]",translation:"горло",example:"La garganta me pica.",exampleTranslation:"У меня першит в горле."},
    {topic:"body",word:"cerebro",transcription:"[seˈɾe.βɾo]",translation:"мозг",example:"El cerebro piensa.",exampleTranslation:"Мозг думает."},
    {topic:"body",word:"músculo",transcription:"[ˈmus.ku.lo]",translation:"мышца",example:"El músculo es fuerte.",exampleTranslation:"Мышца сильная."},
    {topic:"body",word:"barbilla",transcription:"[baɾˈβi.ʎa]",translation:"подбородок",example:"Toco mi barbilla.",exampleTranslation:"Я касаюсь подбородка."},
    {topic:"body",word:"mejilla",transcription:"[meˈxi.ʎa]",translation:"щека",example:"La mejilla está roja.",exampleTranslation:"Щека красная."},
    {topic:"body",word:"frente",transcription:"[ˈfɾen.te]",translation:"лоб",example:"La frente está caliente.",exampleTranslation:"Лоб горячий."},
    {topic:"body",word:"ceja",transcription:"[ˈse.xa]",translation:"бровь",example:"La ceja es negra.",exampleTranslation:"Бровь чёрная."},
    {topic:"body",word:"pestaña",transcription:"[pesˈta.ɲa]",translation:"ресница",example:"La pestaña es larga.",exampleTranslation:"Ресница длинная."},
    {topic:"body",word:"muñeca",transcription:"[muˈɲe.ka]",translation:"запястье",example:"Me duele la muñeca.",exampleTranslation:"У меня болит запястье."},
    {topic:"body",word:"cintura",transcription:"[sinˈtu.ɾa]",translation:"талия",example:"La cintura es fina.",exampleTranslation:"Талия тонкая."},
    {topic:"body",word:"cadera",transcription:"[kaˈðe.ɾa]",translation:"бедро",example:"La cadera me duele.",exampleTranslation:"Бедро болит."},
    {topic:"body",word:"talón",transcription:"[taˈlon]",translation:"пятка",example:"El talón está seco.",exampleTranslation:"Пятка сухая."},
    {topic:"body",word:"pulmón",transcription:"[pulˈmon]",translation:"лёгкое",example:"El pulmón respira aire.",exampleTranslation:"Лёгкое дышит воздухом."},
    {topic:"body",word:"hígado",transcription:"[ˈi.ɣa.ðo]",translation:"печень",example:"El hígado es grande.",exampleTranslation:"Печень большая."},
    {topic:"body",word:"riñón",transcription:"[riˈɲon]",translation:"почка",example:"El riñón funciona bien.",exampleTranslation:"Почка работает хорошо."},
    {topic:"body",word:"vena",transcription:"[ˈbe.na]",translation:"вена",example:"La vena es azul.",exampleTranslation:"Вена синяя."},
    {topic:"body",word:"barba",transcription:"[ˈbaɾ.βa]",translation:"борода",example:"Él tiene barba.",exampleTranslation:"У него есть борода."},
    {topic:"body",word:"bigote",transcription:"[biˈɣo.te]",translation:"усы",example:"El bigote es largo.",exampleTranslation:"Усы длинные."},
    {topic:"body",word:"esqueleto",transcription:"[es.keˈle.to]",translation:"скелет",example:"El esqueleto es duro.",exampleTranslation:"Скелет твёрдый."},
    {topic:"body",word:"costilla",transcription:"[kosˈti.ʎa]",translation:"ребро",example:"Me duele una costilla.",exampleTranslation:"У меня болит ребро."},
    {topic:"body",word:"palma",transcription:"[ˈpal.ma]",translation:"ладонь",example:"La palma de la mano está limpia.",exampleTranslation:"Ладонь чистая."},
    {topic:"body",word:"ombligo",transcription:"[omˈbli.ɣo]",translation:"пупок",example:"El ombligo está aquí.",exampleTranslation:"Пупок находится здесь."},

    // --- CLOTHES (50) ---
    {topic:"clothes",word:"camisa",transcription:"[kaˈmi.sa]",translation:"рубашка",example:"La camisa es blanca.",exampleTranslation:"Рубашка белая."},
    {topic:"clothes",word:"camiseta",transcription:"[ka.miˈse.ta]",translation:"футболка",example:"Llevo una camiseta azul.",exampleTranslation:"На мне синяя футболка."},
    {topic:"clothes",word:"pantalón",transcription:"[pan.taˈlon]",translation:"брюки / штаны",example:"El pantalón es negro.",exampleTranslation:"Брюки чёрные."},
    {topic:"clothes",word:"vestido",transcription:"[besˈti.ðo]",translation:"платье",example:"El vestido es bonito.",exampleTranslation:"Платье красивое."},
    {topic:"clothes",word:"falda",transcription:"[ˈfal.da]",translation:"юбка",example:"La falda es corta.",exampleTranslation:"Юбка короткая."},
    {topic:"clothes",word:"chaqueta",transcription:"[tʃaˈke.ta]",translation:"куртка / пиджак",example:"La chaqueta da calor.",exampleTranslation:"Куртка тёплая."},
    {topic:"clothes",word:"abrigo",transcription:"[aˈβɾi.ɣo]",translation:"пальто",example:"Llevo un abrigo grande.",exampleTranslation:"На мне большое пальто."},
    {topic:"clothes",word:"zapatos",transcription:"[saˈpa.tos]",translation:"туфли / обувь",example:"Los zapatos son nuevos.",exampleTranslation:"Обувь новая."},
    {topic:"clothes",word:"zapatillas",transcription:"[sa.paˈti.ʎas]",translation:"кроссовки / кеды",example:"Uso zapatillas para correr.",exampleTranslation:"Я использую кроссовки для бега."},
    {topic:"clothes",word:"calcetines",transcription:"[kal.seˈti.nes]",translation:"носки",example:"Los calcetines son calientes.",exampleTranslation:"Носки тёплые."},
    {topic:"clothes",word:"sombrero",transcription:"[somˈbɾe.ɾo]",translation:"шляпа",example:"El sombrero me protege del sol.",exampleTranslation:"Шляпа защищает меня от солнца."},
    {topic:"clothes",word:"gorra",transcription:"[ˈgo.ra]",translation:"кепка",example:"La gorra es roja.",exampleTranslation:"Кепка красная."},
    {topic:"clothes",word:"bufanda",transcription:"[buˈfan.da]",translation:"шарф",example:"La bufanda es suave.",exampleTranslation:"Шарф мягкий."},
    {topic:"clothes",word:"guantes",transcription:"[ˈɡwan.tes]",translation:"перчатки",example:"Uso guantes en invierno.",exampleTranslation:"Я ношу перчатки зимой."},
    {topic:"clothes",word:"cinturón",transcription:"[sin.tuˈɾon]",translation:"ремень",example:"El cinturón es de cuero.",exampleTranslation:"Ремень кожаный."},
    {topic:"clothes",word:"corbata",transcription:"[koɾˈβa.ta]",translation:"галстук",example:"Llevo una corbata azul.",exampleTranslation:"На мне синий галстук."},
    {topic:"clothes",word:"pijama",transcription:"[piˈxa.ma]",translation:"пижама",example:"El pijama es cómodo.",exampleTranslation:"Пижама удобная."},
    {topic:"clothes",word:"traje de baño",transcription:"[ˈtɾa.xe ðe ˈba.ɲo]",translation:"купальник / плавки",example:"Compro un traje de baño.",exampleTranslation:"Я покупаю купальник."},
    {topic:"clothes",word:"ropa interior",transcription:"[ˈro.pa in.teˈɾjoɾ]",translation:"нижнее бельё",example:"La ropa interior es limpia.",exampleTranslation:"Нижнее бельё чистое."},
    {topic:"clothes",word:"bota",transcription:"[ˈbo.ta]",translation:"ботинок / сапог",example:"La bota es de cuero.",exampleTranslation:"Сапог кожаный."},
    {topic:"clothes",word:"sandalia",transcription:"[sanˈda.lja]",translation:"сандалия",example:"Uso sandalia en verano.",exampleTranslation:"Я ношу сандалии летом."},
    {topic:"clothes",word:"jersey",transcription:"[xeɾˈsei̯]",translation:"свитер / джемпер",example:"El jersey es caliente.",exampleTranslation:"Свитер тёплый."},
    {topic:"clothes",word:"sudadera",transcription:"[su.ðaˈðe.ɾa]",translation:"толстовка / худи",example:"La sudadera es gris.",exampleTranslation:"Толстовка серая."},
    {topic:"clothes",word:"traje",transcription:"[ˈtɾa.xe]",translation:"костюм",example:"El traje es elegante.",exampleTranslation:"Костюм элегантный."},
    {topic:"clothes",word:"bolso",transcription:"[ˈbol.so]",translation:"сумка (дамская)",example:"El bolso es negro.",exampleTranslation:"Сумка чёрная."},
    {topic:"clothes",word:"cartera",transcription:"[kaɾˈte.ɾa]",translation:"кошелёк / портфель",example:"La cartera está en la mesa.",exampleTranslation:"Кошелёк на столе."},
    {topic:"clothes",word:"gafas",transcription:"[ˈɡa.fas]",translation:"очки",example:"Llevo gafas para leer.",exampleTranslation:"Я ношу очки для чтения."},
    {topic:"clothes",word:"gafas de sol",transcription:"[ˈɡa.fas ðe sol]",translation:"солнцезащитные очки",example:"Uso gafas de sol.",exampleTranslation:"Я ношу солнцезащитные очки."},
    {topic:"clothes",word:"reloj de pulsera",transcription:"[reˈlox ðe pulˈse.ɾa]",translation:"наручные часы",example:"El reloj de pulsera es caro.",exampleTranslation:"Наручные часы дорогие."},
    {topic:"clothes",word:"anillo",transcription:"[aˈni.ʎo]",translation:"кольцо",example:"El anillo es de oro.",exampleTranslation:"Кольцо из золота."},
    {topic:"clothes",word:"collar",transcription:"[koˈʎaɾ]",translation:"ожерелье",example:"El collar es bonito.",exampleTranslation:"Ожерелье красивое."},
    {topic:"clothes",word:"pendiente",transcription:"[penˈdjen.te]",translation:"серьга",example:"El pendiente es de plata.",exampleTranslation:"Серьга из серебра."},
    {topic:"clothes",word:"pulsera",transcription:"[pulˈse.ɾa]",translation:"браслет",example:"La pulsera es roja.",exampleTranslation:"Браслет красный."},
    {topic:"clothes",word:"paraguas",transcription:"[paˈɾa.ɣwas]",translation:"зонт",example:"Necesito un paraguas.",exampleTranslation:"Мне нужен зонт."},
    {topic:"clothes",word:"chándal",transcription:"[ˈtʃan.dal]",translation:"спортивный костюм",example:"Uso un chándal.",exampleTranslation:"Я ношу спортивный костюм."},
    {topic:"clothes",word:"chaleco",transcription:"[tʃaˈle.ko]",translation:"жилет",example:"El chaleco es caliente.",exampleTranslation:"Жилет тёплый."},
    {topic:"clothes",word:"abrigo de piel",transcription:"[aˈβɾi.ɣo ðe pjel]",translation:"шуба",example:"El abrigo de piel da calor.",exampleTranslation:"Шуба согревает."},
    {topic:"clothes",word:"pantalones cortos",transcription:"[pan.taˈlo.nes ˈkoɾ.tos]",translation:"шорты",example:"Uso pantalones cortos.",exampleTranslation:"Я ношу шорты."},
    {topic:"clothes",word:"vaqueros",transcription:"[baˈke.ɾos]",translation:"джинсы",example:"Los vaqueros son azules.",exampleTranslation:"Джинсы синие."},
    {topic:"clothes",word:"blusa",transcription:"[ˈblu.sa]",translation:"блузка",example:"La blusa es blanca.",exampleTranslation:"Блузка белая."},
    {topic:"clothes",word:"albornoz",transcription:"[al.βoɾˈnos]",translation:"халат",example:"El albornoz es suave.",exampleTranslation:"Халат мягкий."},
    {topic:"clothes",word:"zapatillas de casa",transcription:"[sa.paˈti.ʎas ðe ˈka.sa]",translation:"тапочки",example:"Uso zapatillas de casa.",exampleTranslation:"Я ношу домашние тапочки."},
    {topic:"clothes",word:"gorro",transcription:"[ˈgo.ro]",translation:"вязаная шапка",example:"El gorro es de lana.",exampleTranslation:"Шапка шерстяная."},
    {topic:"clothes",word:"botas de agua",transcription:"[ˈbo.tas ðe ˈa.ɣwa]",translation:"резиновые сапоги",example:"Llevo botas de agua.",exampleTranslation:"На мне резиновые сапоги."},
    {topic:"clothes",word:"mallas",transcription:"[ˈma.ʎas]",translation:"легинсы",example:"Las mallas son cómodas.",exampleTranslation:"Легинсы удобные."},
    {topic:"clothes",word:"impermeable",transcription:"[im.peɾ.meˈa.βle]",translation:"дождевик",example:"El impermeable nos protege.",exampleTranslation:"Дождевик защищает нас."},
    {topic:"clothes",word:"tirantes",transcription:"[tiˈɾan.tes]",translation:"подтяжки",example:"Lleva tirantes.",exampleTranslation:"Он носит подтяжки."},
    {topic:"clothes",word:"pajarita",transcription:"[pa.xaˈɾi.ta]",translation:"галстук-бабочка",example:"La pajarita es negra.",exampleTranslation:"Бабочка чёрная."},
    {topic:"clothes",word:"vestido de noche",transcription:"[besˈti.ðo ðe ˈno.tʃe]",translation:"вечернее платье",example:"El vestido de noche es caro.",exampleTranslation:"Вечернее платье дорогое."},
    {topic:"clothes",word:"capa",transcription:"[ˈka.pa]",translation:"плащ / накидка",example:"La capa es larga.",exampleTranslation:"Накидка длинная."},

    // --- TIME (50) ---
    {topic:"time",word:"tiempo",transcription:"[ˈtjem.po]",translation:"время / погода",example:"El tiempo pasa rápido.",exampleTranslation:"Время идет быстро."},
    {topic:"time",word:"hora",transcription:"[ˈo.ɾa]",translation:"час",example:"¿Qué hora es?",exampleTranslation:"Который час?"},
    {topic:"time",word:"minuto",transcription:"[miˈnu.to]",translation:"минута",example:"Un minuto, por favor.",exampleTranslation:"Минутку, пожалуйста."},
    {topic:"time",word:"segundo",transcription:"[seˈɣun.do]",translation:"секунда",example:"Espera un segundo.",exampleTranslation:"Подожди секунду."},
    {topic:"time",word:"día",transcription:"[ˈdi.a]",translation:"день",example:"Hoy es un buen día.",exampleTranslation:"Сегодня хороший день."},
    {topic:"time",word:"noche",transcription:"[ˈno.tʃe]",translation:"ночь",example:"La noche es tranquila.",exampleTranslation:"Ночь спокойная."},
    {topic:"time",word:"mañana",transcription:"[maˈɲa.na]",translation:"утро / завтра",example:"Nos vemos mañana.",exampleTranslation:"Увидимся завтра."},
    {topic:"time",word:"tarde",transcription:"[ˈtaɾ.ðe]",translation:"день / вечер / поздно",example:"Buenas tardes.",exampleTranslation:"Добрый день."},
    {topic:"time",word:"semana",transcription:"[seˈma.na]",translation:"неделя",example:"Esta semana trabajo.",exampleTranslation:"На этой неделе я работаю."},
    {topic:"time",word:"mes",transcription:"[mes]",translation:"месяц",example:"El mes que viene.",exampleTranslation:"В следующем месяце."},
    {topic:"time",word:"año",transcription:"[ˈa.ɲo]",translation:"год",example:"Feliz año nuevo.",exampleTranslation:"С Новым годом."},
    {topic:"time",word:"hoy",transcription:"[oi̯]",translation:"сегодня",example:"Hoy es lunes.",exampleTranslation:"Сегодня понедельник."},
    {topic:"time",word:"ayer",transcription:"[aˈjeɾ]",translation:"вчера",example:"Ayer fue domingo.",exampleTranslation:"Вчера было воскресенье."},
    {topic:"time",word:"ahora",transcription:"[aˈo.ɾa]",translation:"сейчас",example:"Ahora voy a casa.",exampleTranslation:"Сейчас я иду домой."},
    {topic:"time",word:"siempre",transcription:"[ˈsjem.pɾe]",translation:"всегда",example:"Siempre llego a tiempo.",exampleTranslation:"Я всегда прихожу вовремя."},
    {topic:"time",word:"nunca",transcription:"[ˈnun.ka]",translation:"никогда",example:"Nunca como carne.",exampleTranslation:"Я никогда не ем мясо."},
    {topic:"time",word:"a veces",transcription:"[a ˈbe.ses]",translation:"иногда",example:"A veces tomo té.",exampleTranslation:"Иногда я пью чай."},
    {topic:"time",word:"pronto",transcription:"[ˈpɾon.to]",translation:"скоро",example:"Llego pronto.",exampleTranslation:"Я скоро буду."},
    {topic:"time",word:"temprano",transcription:"[temˈpɾa.no]",translation:"рано",example:"Me levanto temprano.",exampleTranslation:"Я встаю рано."},
    {topic:"time",word:"futuro",transcription:"[fuˈtu.ɾo]",translation:"будущее",example:"El futuro es brillante.",exampleTranslation:"Будущее светлое."},
    {topic:"time",word:"pasado",transcription:"[paˈsa.ðo]",translation:"прошлое",example:"El pasado quedó atrás.",exampleTranslation:"Прошлое осталось позади."},
    {topic:"time",word:"presente",transcription:"[pɾeˈsen.te]",translation:"настоящее",example:"Vivo en el presente.",exampleTranslation:"Я живу в настоящем."},
    {topic:"time",word:"siglo",transcription:"[ˈsi.ɣlo]",translation:"век",example:"Estamos en el siglo veintiuno.",exampleTranslation:"Мы в двадцать первом веке."},
    {topic:"time",word:"década",transcription:"[ˈde.ka.ða]",translation:"десятилетие",example:"Ha pasado una década.",exampleTranslation:"Прошло десятилетие."},
    {topic:"time",word:"momento",transcription:"[moˈmen.to]",translation:"момент",example:"Un momento, por favor.",exampleTranslation:"Один момент, пожалуйста."},
    {topic:"time",word:"madrugada",transcription:"[ma.ðɾuˈɣa.ða]",translation:"раннее утро / рассвет",example:"Trabajo de madrugada.",exampleTranslation:"Я работаю ранним утром."},
    {topic:"time",word:"mediodía",transcription:"[me.ðjoˈði.a]",translation:"полдень",example:"Almorzamos al mediodía.",exampleTranslation:"Мы обедаем в полдень."},
    {topic:"time",word:"medianoche",transcription:"[me.ðjaˈno.tʃe]",translation:"полночь",example:"Son las doce, es medianoche.",exampleTranslation:"Сейчас двенадцать, это полночь."},
    {topic:"time",word:"fin de semana",transcription:"[fin de seˈma.na]",translation:"выходные",example:"Buen fin de semana.",exampleTranslation:"Хороших выходных."},
    {topic:"time",word:"estación del año",transcription:"[es.taˈsjon del ˈa.ɲo]",translation:"время года",example:"Mi estación del año favorita es el verano.",exampleTranslation:"Моё любимое время года — лето."},
    {topic:"time",word:"primavera",transcription:"[pɾi.maˈβe.ɾa]",translation:"весна",example:"La primavera es verde.",exampleTranslation:"Весна зелёная."},
    {topic:"time",word:"verano",transcription:"[beˈɾa.no]",translation:"лето",example:"Hace calor en verano.",exampleTranslation:"Летом жарко."},
    {topic:"time",word:"otoño",transcription:"[oˈto.ɲo]",translation:"осень",example:"En otoño caen las hojas.",exampleTranslation:"Осенью опадают листья."},
    {topic:"time",word:"invierno",transcription:"[imˈbjeɾ.no]",translation:"зима",example:"En invierno hace frío.",exampleTranslation:"Зимой холодно."},
    {topic:"time",word:"lunes",transcription:"[ˈlu.nes]",translation:"понедельник",example:"Hoy es lunes.",exampleTranslation:"Сегодня понедельник."},
    {topic:"time",word:"martes",transcription:"[ˈmaɾ.tes]",translation:"вторник",example:"Mañana es martes.",exampleTranslation:"Завтра вторник."},
    {topic:"time",word:"miércoles",transcription:"[ˈmjeɾ.ko.les]",translation:"среда",example:"Trabajo el miércoles.",exampleTranslation:"Я работаю в среду."},
    {topic:"time",word:"jueves",transcription:"[ˈxwe.βes]",translation:"четверг",example:"Nos vemos el jueves.",exampleTranslation:"Увидимся в четверг."},
    {topic:"time",word:"viernes",transcription:"[ˈbjeɾ.nes]",translation:"пятница",example:"Por fin es viernes.",exampleTranslation:"Наконец-то пятница."},
    {topic:"time",word:"sábado",transcription:"[ˈsa.βa.ðo]",translation:"суббота",example:"El sábado descanso.",exampleTranslation:"В субботу я отдыхаю."},
    {topic:"time",word:"domingo",transcription:"[doˈmiŋ.ɡo]",translation:"воскресенье",example:"El domingo voy al parque.",exampleTranslation:"В воскресенье я иду в парк."},
    {topic:"time",word:"enero",transcription:"[eˈne.ɾo]",translation:"январь",example:"Enero es el primer mes.",exampleTranslation:"Январь — первый месяц."},
    {topic:"time",word:"febrero",transcription:"[feˈβɾe.ɾo]",translation:"февраль",example:"Febrero es corto.",exampleTranslation:"Февраль короткий."},
    {topic:"time",word:"marzo",transcription:"[ˈmaɾ.so]",translation:"март",example:"En marzo llega la primavera.",exampleTranslation:"В марте приходит весна."},
    {topic:"time",word:"abril",transcription:"[aˈβɾil]",translation:"апрель",example:"En abril llueve mucho.",exampleTranslation:"В апреле часто идёт дождь."},
    {topic:"time",word:"mayo",transcription:"[ˈma.jo]",translation:"май",example:"Mayo es cálido.",exampleTranslation:"Май тёплый."},
    {topic:"time",word:"junio",transcription:"[ˈxu.njo]",translation:"июнь",example:"Junio es el inicio del verano.",exampleTranslation:"Июнь — начало лета."},
    {topic:"time",word:"julio",transcription:"[ˈxu.ljo]",translation:"июль",example:"En julio voy a la playa.",exampleTranslation:"В июле я еду на пляж."},
    {topic:"time",word:"agosto",transcription:"[aˈɣos.to]",translation:"август",example:"Agosto es caluroso.",exampleTranslation:"Август жаркий."},
    {topic:"time",word:"septiembre",transcription:"[sepˈtjem.bɾe]",translation:"сентябрь",example:"Septiembre empieza la escuela.",exampleTranslation:"В сентябре начинается школа."}
	],
	
	hideVosotros: false, // true — скрыть строку Vosotros (латиноамериканский вариант)

  pronouns: [
    { key: "yo",       label: "Yo" },
    { key: "tu",       label: "Tú" },
    { key: "el",       label: "Él/Ella" },
    { key: "nosotros", label: "Nosotros" },
    { key: "vosotros", label: "Vosotros" },
    { key: "ellos",    label: "Ellos" }
  ],

  tenses: [
    { key: "presente",   label: "Presente" },
    { key: "indefinido", label: "Pretérito Indefinido" },   // ← переименовали
    { key: "futuro",     label: "Futuro Simple" },
    { key: "continuo",   label: "Presente Continuo" },
    { key: "perfecto",   label: "Pretérito Perfecto" },
    { key: "ir_a",       label: "Ir a + infinitivo" }
  ],

  verbs: {
    // === ПРАВИЛЬНЫЕ: достаточно флага (для чипа «прав./неправ.») ===
    // Порядок важен: первый глагол открывается по умолчанию
    hablar:   { regular: true },
    comer:    { regular: true },
    vivir:    { regular: true },
    trabajar: { regular: true },
    aprender: { regular: true },
    escribir: { regular: true },

    // === НЕПРАВИЛЬНЫЕ: храняем только отклонения от правил ===
    // Присутствует массив времени → берём его; нет → генерим окончаниями
    ser: {
      presente:  ["soy","eres","es","somos","sois","son"],
      indefinido:["fui","fuiste","fue","fuimos","fuisteis","fueron"],
      participle: "sido", gerund: "siendo"
      // futuro регулярный → seré, serás... — сгенерится
    },
    estar: {
      presente:  ["estoy","estás","está","estamos","estáis","están"],
      indefinido:["estuve","estuviste","estuvo","estuvimos","estuvisteis","estuvieron"],
      participle: "estado", gerund: "estando"
    },
    haber: {
      presente:  ["he","has","ha","hemos","habéis","han"],
      indefinido:["hube","hubiste","hubo","hubimos","hubisteis","hubieron"],
      participle: "habido"
    },
    ir: {
      presente:  ["voy","vas","va","vamos","vais","van"],
      indefinido:["fui","fuiste","fue","fuimos","fuisteis","fueron"],
      participle: "ido", gerund: "yendo"
    },
    tener: {
      presente:  ["tengo","tienes","tiene","tenemos","tenéis","tienen"],
      indefinido:["tuve","tuviste","tuvo","tuvimos","tuvisteis","tuvieron"],
      futuro:    ["tendré","tendrás","tendrá","tendremos","tendréis","tendrán"],
      participle: "tenido", gerund: "teniendo"
    },
    hacer: {
      presente:  ["hago","haces","hace","hacemos","hacéis","hacen"],
      indefinido:["hice","hiciste","hizo","hicimos","hicisteis","hicieron"],
      futuro:    ["haré","harás","hará","haremos","haréis","harán"],
      participle: "hecho", gerund: "haciendo"
    },
    venir: {
      presente:  ["vengo","vienes","viene","venimos","venís","vienen"],
      indefinido:["vine","viniste","vino","vinimos","vinisteis","vinieron"],
      futuro:    ["vendré","vendrás","vendrá","vendremos","vendréis","vendrán"],
      participle: "venido", gerund: "viniendo"
    }
    // новые неправильные добавляются по тому же шаблону;
    // для дифтонгов в герундии (dormir→durmiendo) просто
    // пишешь gerund: "durmiendo" вручную
  }
};