const LANG_EN = {
  code: 'en',
  name: 'English',
  cards: [
    // --- FOOD (50) ---
    {topic:"food",word:"apple",transcription:"[ˈæp.əl]",translation:"яблоко",example:"The apple is red.",exampleTranslation:"Яблоко красное."},
    {topic:"food",word:"bread",transcription:"[bred]",translation:"хлеб",example:"I buy fresh bread.",exampleTranslation:"Я покупаю свежий хлеб."},
    {topic:"food",word:"water",transcription:"[ˈwɔː.tər]",translation:"вода",example:"Water is essential.",exampleTranslation:"Вода необходима."},
    {topic:"food",word:"milk",transcription:"[mɪlk]",translation:"молоко",example:"Cats drink milk.",exampleTranslation:"Кошки пьют молоко."},
    {topic:"food",word:"cheese",transcription:"[tʃiːz]",translation:"сыр",example:"I love cheese.",exampleTranslation:"Я люблю сыр."},
    {topic:"food",word:"meat",transcription:"[miːt]",translation:"мясо",example:"He cooks meat well.",exampleTranslation:"Он хорошо готовит мясо."},
    {topic:"food",word:"fish",transcription:"[fɪʃ]",translation:"рыба",example:"Fish live in water.",exampleTranslation:"Рыбы живут в воде."},
    {topic:"food",word:"egg",transcription:"[eɡ]",translation:"яйцо",example:"I eat an egg.",exampleTranslation:"Я ем яйцо."},
    {topic:"food",word:"sugar",transcription:"[ˈʃʊɡ.ər]",translation:"сахар",example:"Sugar is sweet.",exampleTranslation:"Сахар сладкий."},
    {topic:"food",word:"salt",transcription:"[sɒlt]",translation:"соль",example:"Add some salt.",exampleTranslation:"Добавь немного соли."},
    {topic:"food",word:"coffee",transcription:"[ˈkɒf.i]",translation:"кофе",example:"I drink coffee.",exampleTranslation:"Я пью кофе."},
    {topic:"food",word:"tea",transcription:"[tiː]",translation:"чай",example:"Tea is hot.",exampleTranslation:"Чай горячий."},
    {topic:"food",word:"juice",transcription:"[dʒuːs]",translation:"сок",example:"Orange juice is sweet.",exampleTranslation:"Апельсиновый сок сладкий."},
    {topic:"food",word:"fruit",transcription:"[fruːt]",translation:"фрукт",example:"Fruit is healthy.",exampleTranslation:"Фрукты полезны."},
    {topic:"food",word:"vegetable",transcription:"[ˈvedʒ.tə.bəl]",translation:"овощ",example:"Eat your vegetables.",exampleTranslation:"Ешь свои овощи."},
    {topic:"food",word:"potato",transcription:"[pəˈteɪ.təʊ]",translation:"картофель",example:"I peel a potato.",exampleTranslation:"Я чищу картошку."},
    {topic:"food",word:"tomato",transcription:"[təˈmɑː.təʊ]",translation:"помидор",example:"A tomato is red.",exampleTranslation:"Помидор красный."},
    {topic:"food",word:"onion",transcription:"[ˈʌn.jən]",translation:"лук",example:"I chop an onion.",exampleTranslation:"Я режу лук."},
    {topic:"food",word:"carrot",transcription:"[ˈkær.ət]",translation:"морковь",example:"Rabbits eat carrots.",exampleTranslation:"Кролики едят морковь."},
    {topic:"food",word:"rice",transcription:"[raɪs]",translation:"рис",example:"We cook rice.",exampleTranslation:"Мы готовим рис."},
    {topic:"food",word:"pasta",transcription:"[ˈpæs.tə]",translation:"паста",example:"Pasta is from Italy.",exampleTranslation:"Паста из Италии."},
    {topic:"food",word:"butter",transcription:"[ˈbʌt.ər]",translation:"масло",example:"Butter is on bread.",exampleTranslation:"Масло на хлебе."},
    {topic:"food",word:"chicken",transcription:"[ˈtʃɪk.ɪn]",translation:"курица",example:"The chicken is tasty.",exampleTranslation:"Курица вкусная."},
    {topic:"food",word:"beef",transcription:"[biːf]",translation:"говядина",example:"He likes beef.",exampleTranslation:"Он любит говядину."},
    {topic:"food",word:"pork",transcription:"[pɔːk]",translation:"свинина",example:"Pork is meat.",exampleTranslation:"Свинина — это мясо."},
    {topic:"food",word:"soup",transcription:"[suːp]",translation:"суп",example:"The soup is warm.",exampleTranslation:"Суп теплый."},
    {topic:"food",word:"salad",transcription:"[ˈsæl.əd]",translation:"салат",example:"I make a salad.",exampleTranslation:"Я делаю салат."},
    {topic:"food",word:"sandwich",transcription:"[ˈsænd.wɪtʃ]",translation:"бутерброд",example:"A sandwich is quick.",exampleTranslation:"Бутерброд — это быстро."},
    {topic:"food",word:"cake",transcription:"[keɪk]",translation:"торт",example:"The cake is sweet.",exampleTranslation:"Торт сладкий."},
    {topic:"food",word:"cookie",transcription:"[ˈkʊk.i]",translation:"печенье",example:"I want a cookie.",exampleTranslation:"Я хочу печенье."},
    {topic:"food",word:"pie",transcription:"[paɪ]",translation:"пирог",example:"She bakes a pie.",exampleTranslation:"Она печет пирог."},
    {topic:"food",word:"ice cream",transcription:"[ˌaɪs ˈkriːm]",translation:"мороженое",example:"Ice cream is cold.",exampleTranslation:"Мороженое холодное."},
    {topic:"food",word:"banana",transcription:"[bəˈnɑː.nə]",translation:"банан",example:"The monkey eats a banana.",exampleTranslation:"Обезьяна ест банан."},
    {topic:"food",word:"orange",transcription:"[ˈɒr.ɪndʒ]",translation:"апельсин",example:"An orange is round.",exampleTranslation:"Апельсин круглый."},
    {topic:"food",word:"lemon",transcription:"[ˈlem.ən]",translation:"лимон",example:"A lemon is sour.",exampleTranslation:"Лимон кислый."},
    {topic:"food",word:"grape",transcription:"[ɡreɪp]",translation:"виноград",example:"Grapes are purple.",exampleTranslation:"Виноград фиолетовый."},
    {topic:"food",word:"strawberry",transcription:"[ˈstrɔː.bər.i]",translation:"клубника",example:"I pick a strawberry.",exampleTranslation:"Я собираю клубнику."},
    {topic:"food",word:"pepper",transcription:"[ˈpep.ər]",translation:"перец",example:"The pepper is spicy.",exampleTranslation:"Перец острый."},
    {topic:"food",word:"cucumber",transcription:"[ˈkjuː.kʌm.bər]",translation:"огурец",example:"A cucumber is green.",exampleTranslation:"Огурец зеленый."},
    {topic:"food",word:"cabbage",transcription:"[ˈkæb.ɪdʒ]",translation:"капуста",example:"Cabbage is a vegetable.",exampleTranslation:"Капуста — это овощ."},
    {topic:"food",word:"bean",transcription:"[biːn]",translation:"боб",example:"Beans are protein.",exampleTranslation:"Бобы — это белок."},
    {topic:"food",word:"mushroom",transcription:"[ˈmʌʃ.ruːm]",translation:"гриб",example:"I find a mushroom.",exampleTranslation:"Я нахожу гриб."},
    {topic:"food",word:"corn",transcription:"[kɔːn]",translation:"кукуруза",example:"Corn is yellow.",exampleTranslation:"Кукуруза желтая."},
    {topic:"food",word:"oil",transcription:"[ɔɪl]",translation:"масло",example:"I use oil.",exampleTranslation:"Я использую масло."},
    {topic:"food",word:"flour",transcription:"[ˈflaʊ.ər]",translation:"мука",example:"Flour is white.",exampleTranslation:"Мука белая."},
    {topic:"food",word:"honey",transcription:"[ˈhʌn.i]",translation:"мед",example:"Honey is sweet.",exampleTranslation:"Мед сладкий."},
    {topic:"food",word:"yogurt",transcription:"[ˈjɒɡ.ət]",translation:"йогурт",example:"Yogurt is in the fridge.",exampleTranslation:"Йогурт в холодильнике."},
    {topic:"food",word:"sausage",transcription:"[ˈsɒs.ɪdʒ]",translation:"сосиска",example:"I grill a sausage.",exampleTranslation:"Я жарю сосиску."},
    {topic:"food",word:"chocolate",transcription:"[ˈtʃɒk.lət]",translation:"шоколад",example:"Chocolate is dark.",exampleTranslation:"Шоколад темный."},
    {topic:"food",word:"nut",transcription:"[nʌt]",translation:"орех",example:"A nut is hard.",exampleTranslation:"Орех твердый."},

    // --- HOME (50) ---
    {topic:"home",word:"house",transcription:"[haʊs]",translation:"дом",example:"The house is big.",exampleTranslation:"Дом большой."},
    {topic:"home",word:"apartment",transcription:"[əˈpɑːt.mənt]",translation:"квартира",example:"I rent an apartment.",exampleTranslation:"Я снимаю квартиру."},
    {topic:"home",word:"room",transcription:"[ruːm]",translation:"комната",example:"The room is cozy.",exampleTranslation:"Комната уютная."},
    {topic:"home",word:"kitchen",transcription:"[ˈkɪtʃ.ən]",translation:"кухня",example:"We cook in the kitchen.",exampleTranslation:"Мы готовим на кухне."},
    {topic:"home",word:"bedroom",transcription:"[ˈbed.ruːm]",translation:"спальня",example:"I sleep in the bedroom.",exampleTranslation:"Я сплю в спальне."},
    {topic:"home",word:"bathroom",transcription:"[ˈbɑːθ.ruːm]",translation:"ванная",example:"The bathroom is clean.",exampleTranslation:"Ванная чистая."},
    {topic:"home",word:"living room",transcription:"[ˈlɪv.ɪŋ ruːm]",translation:"гостиная",example:"We watch TV in the living room.",exampleTranslation:"Мы смотрим ТВ в гостиной."},
    {topic:"home",word:"door",transcription:"[dɔːr]",translation:"дверь",example:"Open the door.",exampleTranslation:"Открой дверь."},
    {topic:"home",word:"window",transcription:"[ˈwɪn.dəʊ]",translation:"окно",example:"The window is open.",exampleTranslation:"Окно открыто."},
    {topic:"home",word:"wall",transcription:"[wɔːl]",translation:"стена",example:"The wall is white.",exampleTranslation:"Стена белая."},
    {topic:"home",word:"floor",transcription:"[flɔːr]",translation:"пол",example:"The floor is wooden.",exampleTranslation:"Пол деревянный."},
    {topic:"home",word:"ceiling",transcription:"[ˈsiː.lɪŋ]",translation:"потолок",example:"The ceiling is high.",exampleTranslation:"Потолок высокий."},
    {topic:"home",word:"roof",transcription:"[ruːf]",translation:"крыша",example:"The roof is red.",exampleTranslation:"Крыша красная."},
    {topic:"home",word:"stairs",transcription:"[steəz]",translation:"лестница",example:"The stairs are steep.",exampleTranslation:"Лестница крутая."},
    {topic:"home",word:"garden",transcription:"[ˈɡɑː.dən]",translation:"сад",example:"We sit in the garden.",exampleTranslation:"Мы сидим в саду."},
    {topic:"home",word:"yard",transcription:"[jɑːd]",translation:"двор",example:"The yard is large.",exampleTranslation:"Двор большой."},
    {topic:"home",word:"garage",transcription:"[ˈɡær.ɑːʒ]",translation:"гараж",example:"The car is in the garage.",exampleTranslation:"Машина в гараже."},
    {topic:"home",word:"basement",transcription:"[ˈbeɪs.mənt]",translation:"подвал",example:"It is dark in the basement.",exampleTranslation:"В подвале темно."},
    {topic:"home",word:"attic",transcription:"[ˈæt.ɪk]",translation:"чердак",example:"The attic is dusty.",exampleTranslation:"На чердаке пыльно."},
    {topic:"home",word:"balcony",transcription:"[ˈbæl.kə.ni]",translation:"балкон",example:"I stand on the balcony.",exampleTranslation:"Я стою на балконе."},
    {topic:"home",word:"table",transcription:"[ˈteɪ.bəl]",translation:"стол",example:"The table is round.",exampleTranslation:"Стол круглый."},
    {topic:"home",word:"chair",transcription:"[tʃeər]",translation:"стул",example:"Sit on the chair.",exampleTranslation:"Сядь на стул."},
    {topic:"home",word:"sofa",transcription:"[ˈsəʊ.fə]",translation:"диван",example:"The sofa is soft.",exampleTranslation:"Диван мягкий."},
    {topic:"home",word:"bed",transcription:"[bed]",translation:"кровать",example:"The bed is comfortable.",exampleTranslation:"Кровать удобная."},
    {topic:"home",word:"wardrobe",transcription:"[ˈwɔː.drəʊb]",translation:"шкаф",example:"My clothes are in the wardrobe.",exampleTranslation:"Моя одежда в шкафу."},
    {topic:"home",word:"shelf",transcription:"[ʃelf]",translation:"полка",example:"The book is on the shelf.",exampleTranslation:"Книга на полке."},
    {topic:"home",word:"carpet",transcription:"[ˈkɑː.pɪt]",translation:"ковер",example:"The carpet is thick.",exampleTranslation:"Ковер толстый."},
    {topic:"home",word:"curtain",transcription:"[ˈkɜː.tən]",translation:"штора",example:"Close the curtains.",exampleTranslation:"Закрой шторы."},
    {topic:"home",word:"mirror",transcription:"[ˈmɪr.ər]",translation:"зеркало",example:"I look in the mirror.",exampleTranslation:"Я смотрю в зеркало."},
    {topic:"home",word:"lamp",transcription:"[læmp]",translation:"лампа",example:"Turn on the lamp.",exampleTranslation:"Включи лампу."},
    {topic:"home",word:"clock",transcription:"[klɒk]",translation:"часы",example:"The clock is ticking.",exampleTranslation:"Часы тикают."},
    {topic:"home",word:"pillow",transcription:"[ˈpɪl.əʊ]",translation:"подушка",example:"My pillow is soft.",exampleTranslation:"Моя подушка мягкая."},
    {topic:"home",word:"blanket",transcription:"[ˈblæŋ.kɪt]",translation:"одеяло",example:"I need a blanket.",exampleTranslation:"Мне нужно одеяло."},
    {topic:"home",word:"oven",transcription:"[ˈʌv.ən]",translation:"духовка",example:"The oven is hot.",exampleTranslation:"Духовка горячая."},
    {topic:"home",word:"fridge",transcription:"[frɪdʒ]",translation:"холодильник",example:"The fridge is full.",exampleTranslation:"Холодильник полный."},
    {topic:"home",word:"sink",transcription:"[sɪŋk]",translation:"раковина",example:"Wash hands in the sink.",exampleTranslation:"Мой руки в раковине."},
    {topic:"home",word:"toilet",transcription:"[ˈtɔɪ.lət]",translation:"туалет",example:"Where is the toilet?",exampleTranslation:"Где туалет?"},
    {topic:"home",word:"shower",transcription:"[ˈʃaʊ.ər]",translation:"душ",example:"I take a shower.",exampleTranslation:"Я принимаю душ."},
    {topic:"home",word:"bath",transcription:"[bɑːθ]",translation:"ванна",example:"The bath is warm.",exampleTranslation:"Ванна теплая."},
    {topic:"home",word:"towel",transcription:"[ˈtaʊ.əl]",translation:"полотенце",example:"Dry with a towel.",exampleTranslation:"Вытри полотенцем."},
    {topic:"home",word:"soap",transcription:"[səʊp]",translation:"мыло",example:"Use soap.",exampleTranslation:"Используй мыло."},
    {topic:"home",word:"brush",transcription:"[brʌʃ]",translation:"щетка",example:"I use a hairbrush.",exampleTranslation:"Я использую щетку для волос."},
    {topic:"home",word:"key",transcription:"[kiː]",translation:"ключ",example:"I lost my key.",exampleTranslation:"Я потерял ключ."},
    {topic:"home",word:"lock",transcription:"[lɒk]",translation:"замок",example:"The lock is broken.",exampleTranslation:"Замок сломан."},
    {topic:"home",word:"vase",transcription:"[vɑːz]",translation:"ваза",example:"Flowers are in the vase.",exampleTranslation:"Цветы в вазе."},
    {topic:"home",word:"plant",transcription:"[plɑːnt]",translation:"растение",example:"Water the plant.",exampleTranslation:"Полей растение."},
    {topic:"home",word:"painting",transcription:"[ˈpeɪnt.tɪŋ]",translation:"картина",example:"The painting is old.",exampleTranslation:"Картина старая."},
    {topic:"home",word:"cup",transcription:"[kʌp]",translation:"чашка",example:"I drink from a cup.",exampleTranslation:"Я пью из чашки."},
    {topic:"home",word:"plate",transcription:"[pleɪt]",translation:"тарелка",example:"The plate is empty.",exampleTranslation:"Тарелка пустая."},
    {topic:"home",word:"spoon",transcription:"[spuːn]",translation:"ложка",example:"I eat with a spoon.",exampleTranslation:"Я ем ложкой."},

    // --- STREET (50) ---
    {topic:"street",word:"road",transcription:"[rəʊd]",translation:"дорога",example:"The road is long.",exampleTranslation:"Дорога длинная."},
    {topic:"street",word:"street",transcription:"[striːt]",translation:"улица",example:"Walk down the street.",exampleTranslation:"Иди по улице."},
    {topic:"street",word:"avenue",transcription:"[ˈæv.ə.njuː]",translation:"проспект",example:"The avenue is wide.",exampleTranslation:"Проспект широкий."},
    {topic:"street",word:"crossroad",transcription:"[ˈkrɒs.rəʊd]",translation:"перекресток",example:"Stop at the crossroad.",exampleTranslation:"Остановись на перекрестке."},
    {topic:"street",word:"bridge",transcription:"[brɪdʒ]",translation:"мост",example:"The bridge is high.",exampleTranslation:"Мост высокий."},
    {topic:"street",word:"sidewalk",transcription:"[ˈsaɪd.wɔːk]",translation:"тротуар",example:"Walk on the sidewalk.",exampleTranslation:"Иди по тротуару."},
    {topic:"street",word:"traffic light",transcription:"[ˈtræf.ɪk laɪt]",translation:"светофор",example:"The traffic light is red.",exampleTranslation:"Светофор красный."},
    {topic:"street",word:"sign",transcription:"[saɪn]",translation:"знак",example:"Read the sign.",exampleTranslation:"Прочитай знак."},
    {topic:"street",word:"car",transcription:"[kɑːr]",translation:"машина",example:"The car is fast.",exampleTranslation:"Машина быстрая."},
    {topic:"street",word:"bus",transcription:"[bʌs]",translation:"автобус",example:"I take the bus.",exampleTranslation:"Я еду на автобусе."},
    {topic:"street",word:"truck",transcription:"[trʌk]",translation:"грузовик",example:"The truck is big.",exampleTranslation:"Грузовик большой."},
    {topic:"street",word:"bicycle",transcription:"[ˈbaɪ.sɪ.kəl]",translation:"велосипед",example:"I ride a bicycle.",exampleTranslation:"Я езжу на велосипеде."},
    {topic:"street",word:"motorcycle",transcription:"[ˈməʊ.tə.saɪ.kəl]",translation:"мотоцикл",example:"The motorcycle is loud.",exampleTranslation:"Мотоцикл громкий."},
    {topic:"street",word:"taxi",transcription:"[ˈtæk.si]",translation:"такси",example:"Call a taxi.",exampleTranslation:"Вызови такси."},
    {topic:"street",word:"train",transcription:"[treɪn]",translation:"поезд",example:"The train is late.",exampleTranslation:"Поезд опаздывает."},
    {topic:"street",word:"subway",transcription:"[ˈsʌb.weɪ]",translation:"метро",example:"I use the subway.",exampleTranslation:"Я пользуюсь метро."},
    {topic:"street",word:"plane",transcription:"[pleɪn]",translation:"самолет",example:"The plane flies high.",exampleTranslation:"Самолет летит высоко."},
    {topic:"street",word:"boat",transcription:"[bəʊt]",translation:"лодка",example:"The boat is on the river.",exampleTranslation:"Лодка на реке."},
    {topic:"street",word:"ship",transcription:"[ʃɪp]",translation:"корабль",example:"The ship is huge.",exampleTranslation:"Корабль огромный."},
    {topic:"street",word:"wheel",transcription:"[wiːl]",translation:"колесо",example:"The wheel is round.",exampleTranslation:"Колесо круглое."},
    {topic:"street",word:"engine",transcription:"[ˈen.dʒɪn]",translation:"двигатель",example:"The engine is running.",exampleTranslation:"Двигатель работает."},
    {topic:"street",word:"tire",transcription:"[ˈtaɪ.ər]",translation:"шина",example:"The tire is flat.",exampleTranslation:"Шина спущена."},
    {topic:"street",word:"steering wheel",transcription:"[ˈstɪə.rɪŋ wiːl]",translation:"руль",example:"Hold the steering wheel.",exampleTranslation:"Держи руль."},
    {topic:"street",word:"pedestrian",transcription:"[pəˈdes.tri.ən]",translation:"пешеход",example:"The pedestrian crosses.",exampleTranslation:"Пешеход переходит."},
    {topic:"street",word:"driver",transcription:"[ˈdraɪ.vər]",translation:"водитель",example:"The driver stops.",exampleTranslation:"Водитель останавливается."},
    {topic:"street",word:"passenger",transcription:"[ˈpæs.ən.dʒər]",translation:"пассажир",example:"The passenger sleeps.",exampleTranslation:"Пассажир спит."},
    {topic:"street",word:"ticket",transcription:"[ˈtɪk.ɪt]",translation:"билет",example:"Buy a ticket.",exampleTranslation:"Купи билет."},
    {topic:"street",word:"station",transcription:"[ˈsteɪ.ʃən]",translation:"станция",example:"We meet at the station.",exampleTranslation:"Мы встречаемся на станции."},
    {topic:"street",word:"airport",transcription:"[ˈeə.pɔːt]",translation:"аэропорт",example:"The airport is busy.",exampleTranslation:"Аэропорт шумный."},
    {topic:"street",word:"harbor",transcription:"[ˈhɑː.bər]",translation:"гавань",example:"Ships are in the harbor.",exampleTranslation:"Корабли в гавани."},
    {topic:"street",word:"park",transcription:"[pɑːk]",translation:"парк",example:"We walk in the park.",exampleTranslation:"Мы гуляем в парке."},
    {topic:"street",word:"shop",transcription:"[ʃɒp]",translation:"магазин",example:"The shop is open.",exampleTranslation:"Магазин открыт."},
    {topic:"street",word:"store",transcription:"[stɔːr]",translation:"магазин",example:"I go to the store.",exampleTranslation:"Я иду в магазин."},
    {topic:"street",word:"market",transcription:"[ˈmɑː.kɪt]",translation:"рынок",example:"The market is loud.",exampleTranslation:"Рынок шумный."},
    {topic:"street",word:"bank",transcription:"[bæŋk]",translation:"банк",example:"I go to the bank.",exampleTranslation:"Я иду в банк."},
    {topic:"street",word:"hospital",transcription:"[ˈhɒs.pɪ.təl]",translation:"больница",example:"He is in the hospital.",exampleTranslation:"Он в больнице."},
    {topic:"street",word:"school",transcription:"[skuːl]",translation:"школа",example:"The school is near.",exampleTranslation:"Школа рядом."},
    {topic:"street",word:"library",transcription:"[ˈlaɪ.brər.i]",translation:"библиотека",example:"I read in the library.",exampleTranslation:"Я читаю в библиотеке."},
    {topic:"street",word:"museum",transcription:"[mjuːˈziː.əm]",translation:"музей",example:"Visit the museum.",exampleTranslation:"Посети музей."},
    {topic:"street",word:"church",transcription:"[tʃɜːtʃ]",translation:"церковь",example:"The church is old.",exampleTranslation:"Церковь старая."},
    {topic:"street",word:"police station",transcription:"[pəˈliːs ˈsteɪ.ʃən]",translation:"полицейский участок",example:"Call the police station.",exampleTranslation:"Звони в участок."},
    {topic:"street",word:"post office",transcription:"[ˈpəʊst ˈɒf.ɪs]",translation:"почта",example:"Send it to the post office.",exampleTranslation:"Отправь это на почту."},
    {topic:"street",word:"restaurant",transcription:"[ˈres.trɒnt]",translation:"ресторан",example:"We eat at the restaurant.",exampleTranslation:"Мы едим в ресторане."},
    {topic:"street",word:"cafe",transcription:"[ˈkæf.eɪ]",translation:"кафе",example:"Meet at the cafe.",exampleTranslation:"Встретимся в кафе."},
    {topic:"street",word:"hotel",transcription:"[həʊˈtel]",translation:"отель",example:"The hotel is nice.",exampleTranslation:"Отель хороший."},
    {topic:"street",word:"cinema",transcription:"[ˈsɪn.ə.mɑː]",translation:"кинотеатр",example:"Go to the cinema.",exampleTranslation:"Иди в кино."},
    {topic:"street",word:"theater",transcription:"[ˈθɪə.tər]",translation:"театр",example:"The theater is full.",exampleTranslation:"Театр полон."},
    {topic:"street",word:"stadium",transcription:"[ˈsteɪ.di.əm]",translation:"стадион",example:"The stadium is huge.",exampleTranslation:"Стадион огромный."},
    {topic:"street",word:"zoo",transcription:"[zuː]",translation:"зоопарк",example:"Kids love the zoo.",exampleTranslation:"Дети любят зоопарк."},
    {topic:"street",word:"pharmacy",transcription:"[ˈfɑː.mə.si]",translation:"аптека",example:"Buy medicine at the pharmacy.",exampleTranslation:"Купи лекарство в аптеке."},

    // --- WORK (50) ---
    {topic:"work",word:"job",transcription:"[dʒɒb]",translation:"работа",example:"He has a job.",exampleTranslation:"У него есть работа."},
    {topic:"work",word:"office",transcription:"[ˈɒf.ɪs]",translation:"офис",example:"I work in an office.",exampleTranslation:"Я работаю в офисе."},
    {topic:"work",word:"boss",transcription:"[bɒs]",translation:"начальник",example:"The boss is strict.",exampleTranslation:"Начальник строгий."},
    {topic:"work",word:"employee",transcription:"[ɪmˈplɔɪ.iː]",translation:"сотрудник",example:"He is a good employee.",exampleTranslation:"Он хороший сотрудник."},
    {topic:"work",word:"colleague",transcription:"[ˈkɒl.iːɡ]",translation:"коллега",example:"My colleague helps me.",exampleTranslation:"Мой коллега помогает мне."},
    {topic:"work",word:"meeting",transcription:"[ˈmiː.tɪŋ]",translation:"собрание",example:"The meeting is long.",exampleTranslation:"Собрание долгое."},
    {topic:"work",word:"task",transcription:"[tɑːsk]",translation:"задача",example:"Finish the task.",exampleTranslation:"Заверши задачу."},
    {topic:"work",word:"project",transcription:"[ˈprɒdʒ.ekt]",translation:"проект",example:"The project is big.",exampleTranslation:"Проект большой."},
    {topic:"work",word:"report",transcription:"[rɪˈpɔːt]",translation:"отчет",example:"Write a report.",exampleTranslation:"Напиши отчет."},
    {topic:"work",word:"deadline",transcription:"[ˈded.laɪn]",translation:"крайний срок",example:"The deadline is tomorrow.",exampleTranslation:"Срок завтра."},
    {topic:"work",word:"computer",transcription:"[kəmˈpjuː.tər]",translation:"компьютер",example:"I use a computer.",exampleTranslation:"Я использую компьютер."},
    {topic:"work",word:"laptop",transcription:"[ˈlæp.tɒp]",translation:"ноутбук",example:"My laptop is new.",exampleTranslation:"Мой ноутбук новый."},
    {topic:"work",word:"printer",transcription:"[ˈprɪn.tər]",translation:"принтер",example:"The printer is broken.",exampleTranslation:"Принтер сломан."},
    {topic:"work",word:"phone",transcription:"[fəʊn]",translation:"телефон",example:"Answer the phone.",exampleTranslation:"Ответь на телефон."},
    {topic:"work",word:"email",transcription:"[ˈiː.meɪl]",translation:"электронное письмо",example:"Send an email.",exampleTranslation:"Отправь электронное письмо."},
    {topic:"work",word:"document",transcription:"[ˈdɒk.jə.mənt]",translation:"документ",example:"Sign the document.",exampleTranslation:"Подпиши документ."},
    {topic:"work",word:"file",transcription:"[faɪl]",translation:"файл",example:"Save the file.",exampleTranslation:"Сохрани файл."},
    {topic:"work",word:"folder",transcription:"[ˈfəʊl.dər]",translation:"папка",example:"Open the folder.",exampleTranslation:"Открой папку."},
    {topic:"work",word:"desk",transcription:"[desk]",translation:"стол",example:"My desk is messy.",exampleTranslation:"Мой стол грязный."},
    {topic:"work",word:"pen",transcription:"[pen]",translation:"ручка",example:"I need a pen.",exampleTranslation:"Мне нужна ручка."},
    {topic:"work",word:"pencil",transcription:"[ˈpen.səl]",translation:"карандаш",example:"The pencil is sharp.",exampleTranslation:"Карандаш острый."},
    {topic:"work",word:"paper",transcription:"[ˈpeɪ.pər]",translation:"бумага",example:"Give me paper.",exampleTranslation:"Дай мне бумагу."},
    {topic:"work",word:"contract",transcription:"[ˈkɒn.trækt]",translation:"контракт",example:"Sign the contract.",exampleTranslation:"Подпиши контракт."},
    {topic:"work",word:"salary",transcription:"[ˈsæl.ər.i]",translation:"зарплата",example:"I got my salary.",exampleTranslation:"Я получил зарплату."},
    {topic:"work",word:"payment",transcription:"[ˈpeɪ.mənt]",translation:"оплата",example:"Make a payment.",exampleTranslation:"Сделай оплату."},
    {topic:"work",word:"schedule",transcription:"[ˈʃed.juːl]",translation:"расписание",example:"Check the schedule.",exampleTranslation:"Проверь расписание."},
    {topic:"work",word:"plan",transcription:"[plæn]",translation:"план",example:"We have a plan.",exampleTranslation:"У нас есть план."},
    {topic:"work",word:"goal",transcription:"[ɡəʊl]",translation:"цель",example:"Reach your goal.",exampleTranslation:"Достигни своей цели."},
    {topic:"work",word:"success",transcription:"[səkˈses]",translation:"успех",example:"Success takes time.",exampleTranslation:"Успех требует времени."},
    {topic:"work",word:"failure",transcription:"[ˈfeɪl.jər]",translation:"провал",example:"Failure is a lesson.",exampleTranslation:"Провал — это урок."},
    {topic:"work",word:"team",transcription:"[tiːm]",translation:"команда",example:"Our team wins.",exampleTranslation:"Наша команда побеждает."},
    {topic:"work",word:"leader",transcription:"[ˈliː.dər]",translation:"лидер",example:"He is a good leader.",exampleTranslation:"Он хороший лидер."},
    {topic:"work",word:"manager",transcription:"[ˈmæn.ɪ.dʒər]",translation:"менеджер",example:"Ask the manager.",exampleTranslation:"Спроси менеджера."},
    {topic:"work",word:"client",transcription:"[ˈklaɪ.ənt]",translation:"клиент",example:"The client is happy.",exampleTranslation:"Клиент доволен."},
    {topic:"work",word:"customer",transcription:"[ˈkʌs.tə.mər]",translation:"покупатель",example:"Help the customer.",exampleTranslation:"Помоги покупателю."},
    {topic:"work",word:"service",transcription:"[ˈsɜː.vɪs]",translation:"сервис",example:"The service is fast.",exampleTranslation:"Сервис быстрый."},
    {topic:"work",word:"business",transcription:"[ˈbɪz.nɪs]",translation:"бизнес",example:"Business is growing.",exampleTranslation:"Бизнес растет."},
    {topic:"work",word:"company",transcription:"[ˈkʌm.pə.ni]",translation:"компания",example:"I work for a company.",exampleTranslation:"Я работаю в компании."},
    {topic:"work",word:"factory",transcription:"[ˈfæk.tər.i]",translation:"фабрика",example:"The factory is loud.",exampleTranslation:"На фабрике шумно."},
    {topic:"work",word:"machine",transcription:"[məˈʃiːn]",translation:"машина",example:"The machine works.",exampleTranslation:"Машина работает."},
    {topic:"work",word:"tool",transcription:"[tuːl]",translation:"инструмент",example:"Use the right tool.",exampleTranslation:"Используй правильный инструмент."},
    {topic:"work",word:"skill",transcription:"[skɪl]",translation:"навык",example:"Learn a new skill.",exampleTranslation:"Изучи новый навык."},
    {topic:"work",word:"experience",transcription:"[ɪkˈspɪə.ri.əns]",translation:"опыт",example:"He has experience.",exampleTranslation:"У него есть опыт."},
    {topic:"work",word:"practice",transcription:"[ˈpræk.tɪs]",translation:"практика",example:"Practice makes perfect.",exampleTranslation:"Практика делает совершенным."},
    {topic:"work",word:"interview",transcription:"[ˈɪn.tə.vjuː]",translation:"собеседование",example:"I have an interview.",exampleTranslation:"У меня собеседование."},
    {topic:"work",word:"resume",transcription:"[ˈrez.ə.meɪ]",translation:"резюме",example:"Update your resume.",exampleTranslation:"Обнови резюме."},
    {topic:"work",word:"vacation",transcription:"[vəˈkeɪ.ʃən]",translation:"отпуск",example:"I need a vacation.",exampleTranslation:"Мне нужен отпуск."},
    {topic:"work",word:"break",transcription:"[breɪk]",translation:"перерыв",example:"Take a break.",exampleTranslation:"Сделай перерыв."},
    {topic:"work",word:"overtime",transcription:"[ˈəʊ.və.taɪm]",translation:"сверхурочная работа",example:"I work overtime.",exampleTranslation:"Я работаю сверхурочно."},

    // --- TRAVEL (50) ---
    {topic:"travel",word:"journey",transcription:"[ˈdʒɜː.ni]",translation:"путешествие",example:"The journey was long.",exampleTranslation:"Путешествие было долгим."},
    {topic:"travel",word:"trip",transcription:"[trɪp]",translation:"поездка",example:"We plan a trip.",exampleTranslation:"Мы планируем поездку."},
    {topic:"travel",word:"tour",transcription:"[tʊər]",translation:"тур",example:"Join the tour.",exampleTranslation:"Присоединись к туру."},
    {topic:"travel",word:"map",transcription:"[mæp]",translation:"карта",example:"Look at the map.",exampleTranslation:"Посмотри на карту."},
    {topic:"travel",word:"compass",transcription:"[ˈkʌm.pəs]",translation:"компас",example:"Use a compass.",exampleTranslation:"Используй компас."},
    {topic:"travel",word:"passport",transcription:"[ˈpɑːs.pɔːt]",translation:"паспорт",example:"Show your passport.",exampleTranslation:"Покажи паспорт."},
    {topic:"travel",word:"visa",transcription:"[ˈviː.zə]",translation:"виза",example:"I need a visa.",exampleTranslation:"Мне нужна виза."},
    {topic:"travel",word:"luggage",transcription:"[ˈlʌɡ.ɪdʒ]",translation:"багаж",example:"Where is my luggage?",exampleTranslation:"Где мой багаж?"},
    {topic:"travel",word:"suitcase",transcription:"[ˈsuːt.keɪs]",translation:"чемодан",example:"Pack the suitcase.",exampleTranslation:"Собери чемодан."},
    {topic:"travel",word:"backpack",transcription:"[ˈbæk.pæk]",translation:"рюкзак",example:"My backpack is heavy.",exampleTranslation:"Мой рюкзак тяжелый."},
    {topic:"travel",word:"camera",transcription:"[ˈkæm.rə]",translation:"камера",example:"Bring a camera.",exampleTranslation:"Возьми камеру."},
    {topic:"travel",word:"tent",transcription:"[tent]",translation:"палатка",example:"Pitch the tent.",exampleTranslation:"Поставь палатку."},
    {topic:"travel",word:"camp",transcription:"[kæmp]",translation:"лагерь",example:"We sleep in a camp.",exampleTranslation:"Мы спим в лагере."},
    {topic:"travel",word:"hotel",transcription:"[həʊˈtel]",translation:"отель",example:"Book a hotel.",exampleTranslation:"Забронируй отель."},
    {topic:"travel",word:"motel",transcription:"[məʊˈtel]",translation:"мотель",example:"Stop at a motel.",exampleTranslation:"Остановись в мотеле."},
    {topic:"travel",word:"hostel",transcription:"[ˈhɒs.təl]",translation:"хостел",example:"Stay in a hostel.",exampleTranslation:"Остановись в хостеле."},
    {topic:"travel",word:"reservation",transcription:"[ˌrez.əˈveɪ.ʃən]",translation:"бронирование",example:"Make a reservation.",exampleTranslation:"Сделай бронирование."},
    {topic:"travel",word:"guide",transcription:"[ɡaɪd]",translation:"гид",example:"The guide explains.",exampleTranslation:"Гид объясняет."},
    {topic:"travel",word:"excursion",transcription:"[ɪkˈskɜː.ʃən]",translation:"экскурсия",example:"Go on an excursion.",exampleTranslation:"Сходи на экскурсию."},
    {topic:"travel",word:"beach",transcription:"[biːtʃ]",translation:"пляж",example:"Relax on the beach.",exampleTranslation:"Расслабься на пляже."},
    {topic:"travel",word:"sea",transcription:"[siː]",translation:"море",example:"The sea is blue.",exampleTranslation:"Море синее."},
    {topic:"travel",word:"ocean",transcription:"[ˈəʊ.ʃən]",translation:"океан",example:"The ocean is deep.",exampleTranslation:"Океан глубокий."},
    {topic:"travel",word:"mountain",transcription:"[ˈmaʊn.tɪn]",translation:"гора",example:"Climb the mountain.",exampleTranslation:"Поднимись на гору."},
    {topic:"travel",word:"river",transcription:"[ˈrɪv.ər]",translation:"река",example:"The river is wide.",exampleTranslation:"Река широкая."},
    {topic:"travel",word:"lake",transcription:"[leɪk]",translation:"озеро",example:"Swim in the lake.",exampleTranslation:"Плавай в озере."},
    {topic:"travel",word:"forest",transcription:"[ˈfɒr.ɪst]",translation:"лес",example:"Walk in the forest.",exampleTranslation:"Гуляй в лесу."},
    {topic:"travel",word:"desert",transcription:"[ˈdez.ət]",translation:"пустыня",example:"The desert is hot.",exampleTranslation:"Пустыня жаркая."},
    {topic:"travel",word:"island",transcription:"[ˈaɪ.lənd]",translation:"остров",example:"Live on an island.",exampleTranslation:"Жить на острове."},
    {topic:"travel",word:"city",transcription:"[ˈsɪt.i]",translation:"город",example:"The city is noisy.",exampleTranslation:"Город шумный."},
    {topic:"travel",word:"country",transcription:"[ˈkʌn.tri]",translation:"страна",example:"I love my country.",exampleTranslation:"Я люблю свою страну."},
    {topic:"travel",word:"capital",transcription:"[ˈkæp.ɪ.təl]",translation:"столица",example:"Visit the capital.",exampleTranslation:"Посети столицу."},
    {topic:"travel",word:"border",transcription:"[ˈbɔː.dər]",translation:"граница",example:"Cross the border.",exampleTranslation:"Перейди границу."},
    {topic:"travel",word:"airport",transcription:"[ˈeə.pɔːt]",translation:"аэропорт",example:"We arrive at the airport.",exampleTranslation:"Мы прибываем в аэропорт."},
    {topic:"travel",word:"station",transcription:"[ˈsteɪ.ʃən]",translation:"станция",example:"Meet at the station.",exampleTranslation:"Встретимся на станции."},
    {topic:"travel",word:"port",transcription:"[pɔːt]",translation:"порт",example:"Ships arrive at the port.",exampleTranslation:"Корабли прибывают в порт."},
    {topic:"travel",word:"flight",transcription:"[flaɪt]",translation:"рейс",example:"The flight is delayed.",exampleTranslation:"Рейс задержан."},
    {topic:"travel",word:"delay",transcription:"[dɪˈleɪ]",translation:"задержка",example:"We have a delay.",exampleTranslation:"У нас задержка."},
    {topic:"travel",word:"arrival",transcription:"[əˈraɪ.vəl]",translation:"прибытие",example:"Wait for arrival.",exampleTranslation:"Жди прибытия."},
    {topic:"travel",word:"departure",transcription:"[dɪˈpɑː.tʃər]",translation:"отправление",example:"Check departure time.",exampleTranslation:"Проверь время отправления."},
    {topic:"travel",word:"foreign",transcription:"[ˈfɒr.ən]",translation:"иностранный",example:"Learn a foreign language.",exampleTranslation:"Учи иностранный язык."},
    {topic:"travel",word:"local",transcription:"[ˈləʊ.kəl]",translation:"местный",example:"Eat local food.",exampleTranslation:"Ешь местную еду."},
    {topic:"travel",word:"tourist",transcription:"[ˈtʊər.ɪst]",translation:"турист",example:"The tourist takes photos.",exampleTranslation:"Турист делает фото."},
    {topic:"travel",word:"attraction",transcription:"[əˈtræk.ʃən]",translation:"достопримечательность",example:"Visit the attraction.",exampleTranslation:"Посети достопримечательность."},
    {topic:"travel",word:"souvenir",transcription:"[ˌsuː.vəˈnɪər]",translation:"сувенир",example:"Buy a souvenir.",exampleTranslation:"Купи сувенир."},
    {topic:"travel",word:"adventure",transcription:"[ədˈven.tʃər]",translation:"приключение",example:"It was an adventure.",exampleTranslation:"Это было приключение."},
    {topic:"travel",word:"route",transcription:"[ruːt]",translation:"маршрут",example:"Plan the route.",exampleTranslation:"Планируй маршрут."},
    {topic:"travel",word:"distance",transcription:"[ˈdɪs.təns]",translation:"расстояние",example:"The distance is short.",exampleTranslation:"Расстояние короткое."},
    {topic:"travel",word:"transport",transcription:"[ˈtræn.spɔːt]",translation:"транспорт",example:"Use public transport.",exampleTranslation:"Используй общественный транспорт."},
    {topic:"travel",word:"currency",transcription:"[ˈkʌr.ən.si]",translation:"валюта",example:"Exchange currency.",exampleTranslation:"Обменяй валюту."},

    // --- FEELINGS (50) ---
    {topic:"feelings",word:"happy",transcription:"[ˈhæp.i]",translation:"счастливый",example:"I am happy.",exampleTranslation:"Я счастлив."},
    {topic:"feelings",word:"sad",transcription:"[sæd]",translation:"грустный",example:"She is sad.",exampleTranslation:"Она грустная."},
    {topic:"feelings",word:"angry",transcription:"[ˈæŋ.ɡri]",translation:"злой",example:"He is angry.",exampleTranslation:"Он злой."},
    {topic:"feelings",word:"calm",transcription:"[kɑːm]",translation:"спокойный",example:"Stay calm.",exampleTranslation:"Оставайся спокойным."},
    {topic:"feelings",word:"excited",transcription:"[ɪkˈsaɪ.tɪd]",translation:"взволнованный",example:"I am excited.",exampleTranslation:"Я взволнован."},
    {topic:"feelings",word:"bored",transcription:"[bɔːd]",translation:"скучающий",example:"I feel bored.",exampleTranslation:"Мне скучно."},
    {topic:"feelings",word:"tired",transcription:"[ˈtaɪəd]",translation:"уставший",example:"I am tired.",exampleTranslation:"Я устал."},
    {topic:"feelings",word:"surprised",transcription:"[səˈpraɪzd]",translation:"удивленный",example:"We are surprised.",exampleTranslation:"Мы удивлены."},
    {topic:"feelings",word:"scared",transcription:"[skeəd]",translation:"напуганный",example:"The dog is scared.",exampleTranslation:"Собака напугана."},
    {topic:"feelings",word:"afraid",transcription:"[əˈfreɪd]",translation:"боящийся",example:"I am afraid.",exampleTranslation:"Я боюсь."},
    {topic:"feelings",word:"brave",transcription:"[breɪv]",translation:"смелый",example:"Be brave.",exampleTranslation:"Будь смелым."},
    {topic:"feelings",word:"shy",transcription:"[ʃaɪ]",translation:"застенчивый",example:"She is shy.",exampleTranslation:"Она застенчивая."},
    {topic:"feelings",word:"proud",transcription:"[praʊd]",translation:"гордый",example:"I am proud.",exampleTranslation:"Я горжусь."},
    {topic:"feelings",word:"lonely",transcription:"[ˈləʊn.li]",translation:"одинокий",example:"He feels lonely.",exampleTranslation:"Ему одиноко."},
    {topic:"feelings",word:"jealous",transcription:"[ˈdʒel.əs]",translation:"ревнивый",example:"Don't be jealous.",exampleTranslation:"Не ревнуй."},
    {topic:"feelings",word:"nervous",transcription:"[ˈnɜː.vəs]",translation:"нервный",example:"I am nervous.",exampleTranslation:"Я нервничаю."},
    {topic:"feelings",word:"relaxed",transcription:"[rɪˈlækst]",translation:"расслабленный",example:"I feel relaxed.",exampleTranslation:"Я расслаблен."},
    {topic:"feelings",word:"confused",transcription:"[kənˈfjuːzd]",translation:"смущенный",example:"I am confused.",exampleTranslation:"Я в замешательстве."},
    {topic:"feelings",word:"disappointed",transcription:"[ˌdɪs.əˈpɔɪn.tɪd]",translation:"разочарованный",example:"She is disappointed.",exampleTranslation:"Она разочарована."},
    {topic:"feelings",word:"grateful",transcription:"[ˈɡreɪt.fəl]",translation:"благодарный",example:"I am grateful.",exampleTranslation:"Я благодарен."},
    {topic:"feelings",word:"love",transcription:"[lʌv]",translation:"любовь",example:"Love is strong.",exampleTranslation:"Любовь сильна."},
    {topic:"feelings",word:"hate",transcription:"[heɪt]",translation:"ненависть",example:"I hate lies.",exampleTranslation:"Я ненавижу ложь."},
    {topic:"feelings",word:"joy",transcription:"[dʒɔɪ]",translation:"радость",example:"Tears of joy.",exampleTranslation:"Слезы радости."},
    {topic:"feelings",word:"sorrow",transcription:"[ˈsɒr.əʊ]",translation:"печаль",example:"Feel the sorrow.",exampleTranslation:"Чувствуй печаль."},
    {topic:"feelings",word:"fear",transcription:"[fɪər]",translation:"страх",example:"Fear is natural.",exampleTranslation:"Страх естественен."},
    {topic:"feelings",word:"hope",transcription:"[həʊp]",translation:"надежда",example:"We have hope.",exampleTranslation:"У нас есть надежда."},
    {topic:"feelings",word:"despair",transcription:"[dɪˈspeər]",translation:"отчаяние",example:"In total despair.",exampleTranslation:"В полном отчаянии."},
    {topic:"feelings",word:"anxiety",transcription:"[æŋˈzaɪ.ə.ti]",translation:"тревога",example:"Anxiety is bad.",exampleTranslation:"Тревога плоха."},
    {topic:"feelings",word:"peace",transcription:"[piːs]",translation:"мир",example:"Peace and quiet.",exampleTranslation:"Мир и покой."},
    {topic:"feelings",word:"rage",transcription:"[reɪdʒ]",translation:"ярость",example:"He felt rage.",exampleTranslation:"Он почувствовал ярость."},
    {topic:"feelings",word:"disgust",transcription:"[dɪsˈɡʌst]",translation:"отвращение",example:"Feel disgust.",exampleTranslation:"Чувствовать отвращение."},
    {topic:"feelings",word:"shame",transcription:"[ʃeɪm]",translation:"стыд",example:"Feel shame.",exampleTranslation:"Чувствовать стыд."},
    {topic:"feelings",word:"guilt",transcription:"[ɡɪlt]",translation:"вина",example:"Sense of guilt.",exampleTranslation:"Чувство вины."},
    {topic:"feelings",word:"pity",transcription:"[ˈpɪt.i]",translation:"жалость",example:"Feel pity.",exampleTranslation:"Чувствовать жалость."},
    {topic:"feelings",word:"envy",transcription:"[ˈen.vi]",translation:"зависть",example:"Envy is ugly.",exampleTranslation:"Зависть уродлива."},
    {topic:"feelings",word:"passion",transcription:"[ˈpæʃ.ən]",translation:"страсть",example:"Follow your passion.",exampleTranslation:"Следуй за страстью."},
    {topic:"feelings",word:"affection",transcription:"[əˈfek.ʃən]",translation:"привязанность",example:"Show affection.",exampleTranslation:"Проявляй привязанность."},
    {topic:"feelings",word:"indifference",transcription:"[ɪnˈdɪf.rəns]",translation:"безразличие",example:"His indifference hurts.",exampleTranslation:"Его безразличие ранит."},
    {topic:"feelings",word:"sympathy",transcription:"[ˈsɪm.pə.θi]",translation:"сочувствие",example:"I feel sympathy.",exampleTranslation:"Я сочувствую."},
    {topic:"feelings",word:"antipathy",transcription:"[ænˈtɪp.ə.θi]",translation:"антипатия",example:"Feel antipathy.",exampleTranslation:"Чувствовать антипатию."},
    {topic:"feelings",word:"embarrassment",transcription:"[ɪmˈbær.əs.mənt]",translation:"смущение",example:"Hide embarrassment.",exampleTranslation:"Скрывать смущение."},
    {topic:"feelings",word:"relief",transcription:"[rɪˈliːf]",translation:"облегчение",example:"Sigh of relief.",exampleTranslation:"Вздох облегчения."},
    {topic:"feelings",word:"shock",transcription:"[ʃɒk]",translation:"шок",example:"It was a shock.",exampleTranslation:"Это был шок."},
    {topic:"feelings",word:"awe",transcription:"[ɔː]",translation:"трепет",example:"Stand in awe.",exampleTranslation:"Стоять в трепете."},
    {topic:"feelings",word:"nostalgia",transcription:"[nɒsˈtæl.dʒə]",translation:"ностальгия",example:"Feel nostalgia.",exampleTranslation:"Чувствовать ностальгию."},
    {topic:"feelings",word:"contentment",transcription:"[kənˈtent.mənt]",translation:"удовлетворение",example:"Feel contentment.",exampleTranslation:"Чувствовать удовлетворение."},
    {topic:"feelings",word:"frustration",transcription:"[frʌsˈtreɪ.ʃən]",translation:"разочарование",example:"Express frustration.",exampleTranslation:"Выразить разочарование."},
    {topic:"feelings",word:"optimism",transcription:"[ˈɒp.tɪ.mɪz.əm]",translation:"оптимизм",example:"Have optimism.",exampleTranslation:"Имей оптимизм."},
    {topic:"feelings",word:"pessimism",transcription:"[ˈpes.ɪ.mɪz.əm]",translation:"пессимизм",example:"Avoid pessimism.",exampleTranslation:"Избегай пессимизма."},
    {topic:"feelings",word:"courage",transcription:"[ˈkʌr.ɪdʒ]",translation:"смелость",example:"Show courage.",exampleTranslation:"Прояви смелость."},

    // --- ANIMALS (50) ---
    {topic:"animals",word:"dog",transcription:"[dɒɡ]",translation:"собака",example:"The dog barks.",exampleTranslation:"Собака лает."},
    {topic:"animals",word:"cat",transcription:"[kæt]",translation:"кошка",example:"The cat purrs.",exampleTranslation:"Кошка мурлычет."},
    {topic:"animals",word:"mouse",transcription:"[maʊs]",translation:"мышь",example:"The mouse runs.",exampleTranslation:"Мышь бежит."},
    {topic:"animals",word:"rat",transcription:"[ræt]",translation:"крыса",example:"A rat is big.",exampleTranslation:"Крыса большая."},
    {topic:"animals",word:"cow",transcription:"[kaʊ]",translation:"корова",example:"The cow gives milk.",exampleTranslation:"Корова дает молоко."},
    {topic:"animals",word:"pig",transcription:"[pɪɡ]",translation:"свинья",example:"The pig is dirty.",exampleTranslation:"Свинья грязная."},
    {topic:"animals",word:"horse",transcription:"[hɔːs]",translation:"лошадь",example:"Ride a horse.",exampleTranslation:"Покатайся на лошади."},
    {topic:"animals",word:"sheep",transcription:"[ʃiːp]",translation:"овца",example:"The sheep eats grass.",exampleTranslation:"Овца ест траву."},
    {topic:"animals",word:"goat",transcription:"[ɡəʊt]",translation:"коза",example:"The goat climbs.",exampleTranslation:"Коза лезет."},
    {topic:"animals",word:"chicken",transcription:"[ˈtʃɪk.ɪn]",translation:"курица",example:"The chicken lays eggs.",exampleTranslation:"Курица несет яйца."},
    {topic:"animals",word:"duck",transcription:"[dʌk]",translation:"утка",example:"The duck swims.",exampleTranslation:"Утка плавает."},
    {topic:"animals",word:"goose",transcription:"[ɡuːs]",translation:"гусь",example:"The goose is loud.",exampleTranslation:"Гусь громкий."},
    {topic:"animals",word:"bird",transcription:"[bɜːd]",translation:"птица",example:"The bird flies.",exampleTranslation:"Птица летает."},
    {topic:"animals",word:"fish",transcription:"[fɪʃ]",translation:"рыба",example:"The fish swims.",exampleTranslation:"Рыба плавает."},
    {topic:"animals",word:"frog",transcription:"[frɒɡ]",translation:"лягушка",example:"The frog jumps.",exampleTranslation:"Лягушка прыгает."},
    {topic:"animals",word:"snake",transcription:"[sneɪk]",translation:"змея",example:"The snake hisses.",exampleTranslation:"Змея шипит."},
    {topic:"animals",word:"turtle",transcription:"[ˈtɜː.təl]",translation:"черепаха",example:"The turtle is slow.",exampleTranslation:"Черепаха медленная."},
    {topic:"animals",word:"rabbit",transcription:"[ˈræb.ɪt]",translation:"кролик",example:"The rabbit hops.",exampleTranslation:"Кролик прыгает."},
    {topic:"animals",word:"bear",transcription:"[beər]",translation:"медведь",example:"The bear is huge.",exampleTranslation:"Медведь огромный."},
    {topic:"animals",word:"wolf",transcription:"[wʊlf]",translation:"волк",example:"The wolf howls.",exampleTranslation:"Волк воет."},
    {topic:"animals",word:"fox",transcription:"[fɒks]",translation:"лиса",example:"The fox is red.",exampleTranslation:"Лиса рыжая."},
    {topic:"animals",word:"lion",transcription:"[ˈlaɪ.ən]",translation:"лев",example:"The lion is king.",exampleTranslation:"Лев — царь."},
    {topic:"animals",word:"tiger",transcription:"[ˈtaɪ.ɡər]",translation:"тигр",example:"The tiger hunts.",exampleTranslation:"Тигр охотится."},
    {topic:"animals",word:"elephant",transcription:"[ˈel.ɪ.fənt]",translation:"слон",example:"The elephant is big.",exampleTranslation:"Слон большой."},
    {topic:"animals",word:"monkey",transcription:"[ˈmʌŋ.ki]",translation:"обезьяна",example:"The monkey climbs.",exampleTranslation:"Обезьяна лазает."},
    {topic:"animals",word:"giraffe",transcription:"[dʒɪˈrɑːf]",translation:"жираф",example:"The giraffe is tall.",exampleTranslation:"Жираф высокий."},
    {topic:"animals",word:"zebra",transcription:"[ˈzeb.rə]",translation:"зебра",example:"The zebra runs.",exampleTranslation:"Зебра бежит."},
    {topic:"animals",word:"deer",transcription:"[dɪər]",translation:"олень",example:"The deer is fast.",exampleTranslation:"Олень быстрый."},
    {topic:"animals",word:"kangaroo",transcription:"[ˌkæŋ.ɡəˈruː]",translation:"кенгуру",example:"The kangaroo jumps.",exampleTranslation:"Кенгуру прыгает."},
    {topic:"animals",word:"koala",transcription:"[kəʊˈɑː.lə]",translation:"коала",example:"The koala sleeps.",exampleTranslation:"Коала спит."},
    {topic:"animals",word:"panda",transcription:"[ˈpæn.də]",translation:"панда",example:"The panda eats bamboo.",exampleTranslation:"Панда ест бамбук."},
    {topic:"animals",word:"camel",transcription:"[ˈkæm.əl]",translation:"верблюд",example:"The camel walks.",exampleTranslation:"Верблюд ходит."},
    {topic:"animals",word:"dolphin",transcription:"[ˈdɒl.fɪn]",translation:"дельфин",example:"The dolphin is smart.",exampleTranslation:"Дельфин умный."},
    {topic:"animals",word:"whale",transcription:"[weɪl]",translation:"кит",example:"The whale is huge.",exampleTranslation:"Кит огромный."},
    {topic:"animals",word:"shark",transcription:"[ʃɑːk]",translation:"акула",example:"The shark is dangerous.",exampleTranslation:"Акула опасна."},
    {topic:"animals",word:"octopus",transcription:"[ˈɒk.tə.pəs]",translation:"осьминог",example:"The octopus has arms.",exampleTranslation:"У осьминога есть руки."},
    {topic:"animals",word:"crab",transcription:"[kræb]",translation:"краб",example:"The crab walks sideways.",exampleTranslation:"Краб ходит боком."},
    {topic:"animals",word:"bee",transcription:"[biː]",translation:"пчела",example:"The bee makes honey.",exampleTranslation:"Пчела делает мед."},
    {topic:"animals",word:"ant",transcription:"[ænt]",translation:"муравей",example:"The ant is small.",exampleTranslation:"Муравей маленький."},
    {topic:"animals",word:"butterfly",transcription:"[ˈbʌt.ə.flaɪ]",translation:"бабочка",example:"The butterfly flies.",exampleTranslation:"Бабочка летает."},
    {topic:"animals",word:"spider",transcription:"[ˈspaɪ.dər]",translation:"паук",example:"The spider weaves.",exampleTranslation:"Паук плетет."},
    {topic:"animals",word:"fly",transcription:"[flaɪ]",translation:"муха",example:"The fly buzzes.",exampleTranslation:"Муха жужжит."},
    {topic:"animals",word:"mosquito",transcription:"[məˈskiː.təʊ]",translation:"комар",example:"The mosquito bites.",exampleTranslation:"Комар кусает."},
    {topic:"animals",word:"owl",transcription:"[aʊl]",translation:"сова",example:"The owl hoots.",exampleTranslation:"Сова ухает."},
    {topic:"animals",word:"eagle",transcription:"[ˈiː.ɡəl]",translation:"орел",example:"The eagle soars.",exampleTranslation:"Орел парит."},
    {topic:"animals",word:"parrot",transcription:"[ˈpær.ət]",translation:"попугай",example:"The parrot talks.",exampleTranslation:"Попугай говорит."},
    {topic:"animals",word:"penguin",transcription:"[ˈpeŋ.ɡwɪn]",translation:"пингвин",example:"The penguin waddles.",exampleTranslation:"Пингвин ходит вперевалку."},
    {topic:"animals",word:"squirrel",transcription:"[ˈskwɪr.əl]",translation:"белка",example:"The squirrel climbs.",exampleTranslation:"Белка лазает."},
    {topic:"animals",word:"hedgehog",transcription:"[ˈhedʒ.hɒɡ]",translation:"ежик",example:"The hedgehog is prickly.",exampleTranslation:"Ежик колючий."},
    {topic:"animals",word:"seal",transcription:"[siːl]",translation:"тюлень",example:"The seal swims.",exampleTranslation:"Тюлень плавает."},

    // --- BODY (50) ---
    {topic:"body",word:"head",transcription:"[hed]",translation:"голова",example:"My head hurts.",exampleTranslation:"У меня болит голова."},
    {topic:"body",word:"hair",transcription:"[heər]",translation:"волосы",example:"Cut your hair.",exampleTranslation:"Подстриги волосы."},
    {topic:"body",word:"face",transcription:"[feɪs]",translation:"лицо",example:"Wash your face.",exampleTranslation:"Умой лицо."},
    {topic:"body",word:"eye",transcription:"[aɪ]",translation:"глаз",example:"Close your eyes.",exampleTranslation:"Закрой глаза."},
    {topic:"body",word:"ear",transcription:"[ɪər]",translation:"ухо",example:"Cover your ears.",exampleTranslation:"Закрой уши."},
    {topic:"body",word:"nose",transcription:"[nəʊz]",translation:"нос",example:"Blow your nose.",exampleTranslation:"Высморкайся."},
    {topic:"body",word:"mouth",transcription:"[maʊθ]",translation:"рот",example:"Open your mouth.",exampleTranslation:"Открой рот."},
    {topic:"body",word:"lip",transcription:"[lɪp]",translation:"губа",example:"Bite your lip.",exampleTranslation:"Прикуси губу."},
    {topic:"body",word:"tooth",transcription:"[tuːθ]",translation:"зуб",example:"Brush your teeth.",exampleTranslation:"Чисти зубы."},
    {topic:"body",word:"tongue",transcription:"[tʌŋ]",translation:"язык",example:"Bite your tongue.",exampleTranslation:"Прикуси язык."},
    {topic:"body",word:"neck",transcription:"[nek]",translation:"шея",example:"My neck is stiff.",exampleTranslation:"Моя шея напряжена."},
    {topic:"body",word:"shoulder",transcription:"[ˈʃəʊl.dər]",translation:"плечо",example:"Shrug your shoulders.",exampleTranslation:"Пожми плечами."},
    {topic:"body",word:"arm",transcription:"[ɑːm]",translation:"рука",example:"Lift your arm.",exampleTranslation:"Подними руку."},
    {topic:"body",word:"elbow",transcription:"[ˈel.bəʊ]",translation:"локоть",example:"Rest your elbows.",exampleTranslation:"Поставь локти."},
    {topic:"body",word:"hand",transcription:"[hænd]",translation:"кисть",example:"Wash your hands.",exampleTranslation:"Мой руки."},
    {topic:"body",word:"finger",transcription:"[ˈfɪŋ.ɡər]",translation:"палец",example:"Cut your finger.",exampleTranslation:"Порежь палец."},
    {topic:"body",word:"thumb",transcription:"[θʌm]",translation:"большой палец",example:"Thumbs up.",exampleTranslation:"Палец вверх."},
    {topic:"body",word:"nail",transcription:"[neɪl]",translation:"ноготь",example:"Cut your nails.",exampleTranslation:"Стриги ногти."},
    {topic:"body",word:"chest",transcription:"[tʃest]",translation:"грудь",example:"Chest pain.",exampleTranslation:"Боль в груди."},
    {topic:"body",word:"back",transcription:"[bæk]",translation:"спина",example:"My back hurts.",exampleTranslation:"У меня болит спина."},
    {topic:"body",word:"stomach",transcription:"[ˈstʌm.ək]",translation:"живот",example:"My stomach aches.",exampleTranslation:"У меня болит живот."},
    {topic:"body",word:"leg",transcription:"[leɡ]",translation:"нога",example:"Break your leg.",exampleTranslation:"Сломай ногу."},
    {topic:"body",word:"knee",transcription:"[niː]",translation:"колено",example:"Bend your knee.",exampleTranslation:"Согни колено."},
    {topic:"body",word:"foot",transcription:"[fʊt]",translation:"ступня",example:"Wash your feet.",exampleTranslation:"Мой ноги."},
    {topic:"body",word:"ankle",transcription:"[ˈæŋ.kəl]",translation:"лодыжка",example:"Sprain your ankle.",exampleTranslation:"Растяни лодыжку."},
    {topic:"body",word:"toe",transcription:"[təʊ]",translation:"палец ноги",example:"Stub your toe.",exampleTranslation:"Ушиби палец на ноге."},
    {topic:"body",word:"heel",transcription:"[hiːl]",translation:"пятка",example:"Heel pain.",exampleTranslation:"Боль в пятке."},
    {topic:"body",word:"skin",transcription:"[skɪn]",translation:"кожа",example:"Soft skin.",exampleTranslation:"Мягкая кожа."},
    {topic:"body",word:"bone",transcription:"[bəʊn]",translation:"кость",example:"Broken bone.",exampleTranslation:"Сломанная кость."},
    {topic:"body",word:"blood",transcription:"[blʌd]",translation:"кровь",example:"Draw blood.",exampleTranslation:"Сдай кровь."},
    {topic:"body",word:"heart",transcription:"[hɑːt]",translation:"сердце",example:"Heart beats.",exampleTranslation:"Сердце бьется."},
    {topic:"body",word:"brain",transcription:"[breɪn]",translation:"мозг",example:"Use your brain.",exampleTranslation:"Используй мозг."},
    {topic:"body",word:"lung",transcription:"[lʌŋ]",translation:"легкое",example:"Healthy lungs.",exampleTranslation:"Здоровые легкие."},
    {topic:"body",word:"muscle",transcription:"[ˈmʌs.əl]",translation:"мышца",example:"Build muscle.",exampleTranslation:"Накачай мышцы."},
    {topic:"body",word:"nerve",transcription:"[nɜːv]",translation:"нерв",example:"Nerve damage.",exampleTranslation:"Повреждение нерва."},
    {topic:"body",word:"vein",transcription:"[veɪn]",translation:"вена",example:"Visible veins.",exampleTranslation:"Видимые вены."},
    {topic:"body",word:"kidney",transcription:"[ˈkɪd.ni]",translation:"почка",example:"Kidney stone.",exampleTranslation:"Камень в почке."},
    {topic:"body",word:"liver",transcription:"[ˈlɪv.ər]",translation:"печень",example:"Liver disease.",exampleTranslation:"Болезнь печени."},
    {topic:"body",word:"throat",transcription:"[θrəʊt]",translation:"горло",example:"Sore throat.",exampleTranslation:"Больное горло."},
    {topic:"body",word:"wrist",transcription:"[rɪst]",translation:"запястье",example:"Wrist watch.",exampleTranslation:"Наручные часы."},
    {topic:"body",word:"hip",transcription:"[hɪp]",translation:"бедро",example:"Hip pain.",exampleTranslation:"Боль в бедре."},
    {topic:"body",word:"waist",transcription:"[weɪst]",translation:"талия",example:"Slim waist.",exampleTranslation:"Тонкая талия."},
    {topic:"body",word:"cheek",transcription:"[tʃiːk]",translation:"щека",example:"Rosy cheeks.",exampleTranslation:"Розовые щеки."},
    {topic:"body",word:"chin",transcription:"[tʃɪn]",translation:"подбородок",example:"Rub your chin.",exampleTranslation:"Потри подбородок."},
    {topic:"body",word:"forehead",transcription:"[ˈfɔː.hed]",translation:"лоб",example:"Sweaty forehead.",exampleTranslation:"Потный лоб."},
    {topic:"body",word:"eyelash",transcription:"[ˈaɪ.læʃ]",translation:"ресница",example:"Long eyelashes.",exampleTranslation:"Длинные ресницы."},
    {topic:"body",word:"eyebrow",transcription:"[ˈaɪ.braʊ]",translation:"бровь",example:"Raise eyebrows.",exampleTranslation:"Подними брови."},
    {topic:"body",word:"eyelid",transcription:"[ˈaɪ.lɪd]",translation:"веко",example:"Close eyelids.",exampleTranslation:"Закрой веки."},
    {topic:"body",word:"pupil",transcription:"[ˈpjuː.pɪl]",translation:"зрачок",example:"Dilated pupils.",exampleTranslation:"Расширенные зрачки."},

    // --- CLOTHES (50) ---
    {topic:"clothes",word:"shirt",transcription:"[ʃɜːt]",translation:"рубашка",example:"Iron your shirt.",exampleTranslation:"Погладь рубашку."},
    {topic:"clothes",word:"t-shirt",transcription:"[ˈtiː.ʃɜːt]",translation:"футболка",example:"Wear a t-shirt.",exampleTranslation:"Надень футболку."},
    {topic:"clothes",word:"trousers",transcription:"[ˈtraʊ.zəz]",translation:"брюки",example:"Fold the trousers.",exampleTranslation:"Сложи брюки."},
    {topic:"clothes",word:"jeans",transcription:"[dʒiːnz]",translation:"джинсы",example:"Buy new jeans.",exampleTranslation:"Купи новые джинсы."},
    {topic:"clothes",word:"shorts",transcription:"[ʃɔːts]",translation:"шорты",example:"Summer shorts.",exampleTranslation:"Летние шорты."},
    {topic:"clothes",word:"skirt",transcription:"[skɜːt]",translation:"юбка",example:"Long skirt.",exampleTranslation:"Длинная юбка."},
    {topic:"clothes",word:"dress",transcription:"[dres]",translation:"платье",example:"Beautiful dress.",exampleTranslation:"Красивое платье."},
    {topic:"clothes",word:"jacket",transcription:"[ˈdʒæk.ɪt]",translation:"куртка",example:"Warm jacket.",exampleTranslation:"Теплая куртка."},
    {topic:"clothes",word:"coat",transcription:"[kəʊt]",translation:"пальто",example:"Winter coat.",exampleTranslation:"Зимнее пальто."},
    {topic:"clothes",word:"sweater",transcription:"[ˈswet.ər]",translation:"свитер",example:"Wool sweater.",exampleTranslation:"Шерстяной свитер."},
    {topic:"clothes",word:"raincoat",transcription:"[ˈreɪn.kəʊt]",translation:"плащ",example:"Wear a raincoat.",exampleTranslation:"Надень плащ."},
    {topic:"clothes",word:"suit",transcription:"[suːt]",translation:"костюм",example:"Business suit.",exampleTranslation:"Деловой костюм."},
    {topic:"clothes",word:"tie",transcription:"[taɪ]",translation:"галстук",example:"Loosen your tie.",exampleTranslation:"Ослабь галстук."},
    {topic:"clothes",word:"hat",transcription:"[hæt]",translation:"шляпа",example:"Wear a hat.",exampleTranslation:"Надень шляпу."},
    {topic:"clothes",word:"cap",transcription:"[kæp]",translation:"кепка",example:"Baseball cap.",exampleTranslation:"Бейсболка."},
    {topic:"clothes",word:"scarf",transcription:"[skɑːf]",translation:"шарф",example:"Wrap a scarf.",exampleTranslation:"Оберни шарф."},
    {topic:"clothes",word:"gloves",transcription:"[ɡlʌvz]",translation:"перчатки",example:"Leather gloves.",exampleTranslation:"Кожаные перчатки."},
    {topic:"clothes",word:"socks",transcription:"[sɒks]",translation:"носки",example:"Wear warm socks.",exampleTranslation:"Надень теплые носки."},
    {topic:"clothes",word:"shoes",transcription:"[ʃuːz]",translation:"туфли",example:"Polish your shoes.",exampleTranslation:"Почисти туфли."},
    {topic:"clothes",word:"boots",transcription:"[buːts]",translation:"ботинки",example:"Rain boots.",exampleTranslation:"Резиновые сапоги."},
    {topic:"clothes",word:"sneakers",transcription:"[ˈsniː.kəz]",translation:"кроссовки",example:"Run in sneakers.",exampleTranslation:"Беги в кроссовках."},
    {topic:"clothes",word:"sandals",transcription:"[ˈsæn.dəlz]",translation:"сандалии",example:"Beach sandals.",exampleTranslation:"Пляжные сандалии."},
    {topic:"clothes",word:"heels",transcription:"[hiːlz]",translation:"каблуки",example:"High heels.",exampleTranslation:"Высокие каблуки."},
    {topic:"clothes",word:"underwear",transcription:"[ˈʌn.də.weər]",translation:"нижнее белье",example:"Clean underwear.",exampleTranslation:"Чистое белье."},
    {topic:"clothes",word:"bra",transcription:"[brɑː]",translation:"бюстгальтер",example:"Wear a bra.",exampleTranslation:"Надень бюстгальтер."},
    {topic:"clothes",word:"pajamas",transcription:"[pəˈdʒɑː.məz]",translation:"пижама",example:"Sleep in pajamas.",exampleTranslation:"Спи в пижаме."},
    {topic:"clothes",word:"swimsuit",transcription:"[ˈswɪm.suːt]",translation:"купальник",example:"Buy a swimsuit.",exampleTranslation:"Купи купальник."},
    {topic:"clothes",word:"belt",transcription:"[belt]",translation:"ремень",example:"Leather belt.",exampleTranslation:"Кожаный ремень."},
    {topic:"clothes",word:"button",transcription:"[ˈbʌt.ən]",translation:"пуговица",example:"Sew a button.",exampleTranslation:"Пришей пуговицу."},
    {topic:"clothes",word:"zipper",transcription:"[ˈzɪp.ər]",translation:"молния",example:"Fix the zipper.",exampleTranslation:"Почини молнию."},
    {topic:"clothes",word:"pocket",transcription:"[ˈpɒk.ɪt]",translation:"карман",example:"Empty pocket.",exampleTranslation:"Пустой карман."},
    {topic:"clothes",word:"collar",transcription:"[ˈkɒl.ər]",translation:"воротник",example:"Stiff collar.",exampleTranslation:"Жесткий воротник."},
    {topic:"clothes",word:"sleeve",transcription:"[sliːv]",translation:"рукав",example:"Roll up sleeves.",exampleTranslation:"Засучи рукава."},
    {topic:"clothes",word:"hood",transcription:"[hʊd]",translation:"капюшон",example:"Put on the hood.",exampleTranslation:"Надень капюшон."},
    {topic:"clothes",word:"veil",transcription:"[veɪl]",translation:"вуаль",example:"Bridal veil.",exampleTranslation:"Свадебная вуаль."},
    {topic:"clothes",word:"apron",transcription:"[ˈeɪ.prən]",translation:"фартук",example:"Cook in an apron.",exampleTranslation:"Готовь в фартуке."},
    {topic:"clothes",word:"uniform",transcription:"[ˈjuː.nɪ.fɔːm]",translation:"форма",example:"School uniform.",exampleTranslation:"Школьная форма."},
    {topic:"clothes",word:"costume",transcription:"[ˈkɒs.tjuːm]",translation:"костюм",example:"Halloween costume.",exampleTranslation:"Костюм на Хэллоуин."},
    {topic:"clothes",word:"robe",transcription:"[rəʊb]",translation:"халат",example:"Bath robe.",exampleTranslation:"Банный халат."},
    {topic:"clothes",word:"shawl",transcription:"[ʃɔːl]",translation:"шаль",example:"Woolen shawl.",exampleTranslation:"Шерстяная шаль."},
    {topic:"clothes",word:"mittens",transcription:"[ˈmɪt.ənz]",translation:"варежки",example:"Warm mittens.",exampleTranslation:"Теплые варежки."},
    {topic:"clothes",word:"flip-flops",transcription:"[ˈflɪp.flɒps]",translation:"шлепанцы",example:"Wear flip-flops.",exampleTranslation:"Надень шлепанцы."},
    {topic:"clothes",word:"earmuffs",transcription:"[ˈɪə.mʌfs]",translation:"наушники",example:"Furry earmuffs.",exampleTranslation:"Меховые наушники."},
    {topic:"clothes",word:"glasses",transcription:"[ˈɡlɑː.sɪz]",translation:"очки",example:"Wear glasses.",exampleTranslation:"Носи очки."},
    {topic:"clothes",word:"sunglasses",transcription:"[ˈsʌn.ɡlɑː.sɪz]",translation:"солнечные очки",example:"Dark sunglasses.",exampleTranslation:"Темные очки."},
    {topic:"clothes",word:"watch",transcription:"[wɒtʃ]",translation:"часы",example:"Smart watch.",exampleTranslation:"Умные часы."},
    {topic:"clothes",word:"bracelet",transcription:"[ˈbreɪs.lət]",translation:"браслет",example:"Gold bracelet.",exampleTranslation:"Золотой браслет."},
    {topic:"clothes",word:"ring",transcription:"[rɪŋ]",translation:"кольцо",example:"Diamond ring.",exampleTranslation:"Бриллиантовое кольцо."},
    {topic:"clothes",word:"necklace",transcription:"[ˈnek.ləs]",translation:"ожерелье",example:"Pearl necklace.",exampleTranslation:"Жемчужное ожерелье."},

    // --- TIME (50) ---
    {topic:"time",word:"second",transcription:"[ˈsek.ənd]",translation:"секунда",example:"Wait a second.",exampleTranslation:"Подожди секунду."},
    {topic:"time",word:"minute",transcription:"[ˈmɪn.ɪt]",translation:"минута",example:"Five minutes.",exampleTranslation:"Пять минут."},
    {topic:"time",word:"hour",transcription:"[ˈaʊər]",translation:"час",example:"An hour later.",exampleTranslation:"Час спустя."},
    {topic:"time",word:"day",transcription:"[deɪ]",translation:"день",example:"Have a nice day.",exampleTranslation:"Хорошего дня."},
    {topic:"time",word:"week",transcription:"[wiːk]",translation:"неделя",example:"Next week.",exampleTranslation:"На следующей неделе."},
    {topic:"time",word:"month",transcription:"[mʌnθ]",translation:"месяц",example:"Once a month.",exampleTranslation:"Раз в месяц."},
    {topic:"time",word:"year",transcription:"[jɪər]",translation:"год",example:"New Year.",exampleTranslation:"Новый год."},
    {topic:"time",word:"decade",transcription:"[ˈdek.eɪd]",translation:"десятилетие",example:"Past decade.",exampleTranslation:"Прошлое десятилетие."},
    {topic:"time",word:"century",transcription:"[ˈsen.tʃər.i]",translation:"век",example:"Last century.",exampleTranslation:"Прошлый век."},
    {topic:"time",word:"morning",transcription:"[ˈmɔː.nɪŋ]",translation:"утро",example:"Good morning.",exampleTranslation:"Доброе утро."},
    {topic:"time",word:"afternoon",transcription:"[ˌɑːf.təˈnuːn]",translation:"день",example:"Good afternoon.",exampleTranslation:"Добрый день."},
    {topic:"time",word:"evening",transcription:"[ˈiːv.nɪŋ]",translation:"вечер",example:"Good evening.",exampleTranslation:"Добрый вечер."},
    {topic:"time",word:"night",transcription:"[naɪt]",translation:"ночь",example:"Good night.",exampleTranslation:"Спокойной ночи."},
    {topic:"time",word:"noon",transcription:"[nuːn]",translation:"полдень",example:"At noon.",exampleTranslation:"В полдень."},
    {topic:"time",word:"midnight",transcription:"[ˈmɪd.naɪt]",translation:"полночь",example:"At midnight.",exampleTranslation:"В полночь."},
    {topic:"time",word:"today",transcription:"[təˈdeɪ]",translation:"сегодня",example:"Today is sunny.",exampleTranslation:"Сегодня солнечно."},
    {topic:"time",word:"tomorrow",transcription:"[təˈmɒr.əʊ]",translation:"завтра",example:"See you tomorrow.",exampleTranslation:"Увидимся завтра."},
    {topic:"time",word:"yesterday",transcription:"[ˈjes.tə.deɪ]",translation:"вчера",example:"Yesterday was rainy.",exampleTranslation:"Вчера было дождливо."},
    {topic:"time",word:"Monday",transcription:"[ˈmʌn.deɪ]",translation:"понедельник",example:"On Monday.",exampleTranslation:"В понедельник."},
    {topic:"time",word:"Tuesday",transcription:"[ˈtjuːz.deɪ]",translation:"вторник",example:"On Tuesday.",exampleTranslation:"Во вторник."},
    {topic:"time",word:"Wednesday",transcription:"[ˈwenz.deɪ]",translation:"среда",example:"On Wednesday.",exampleTranslation:"В среду."},
    {topic:"time",word:"Thursday",transcription:"[ˈθɜːz.deɪ]",translation:"четверг",example:"On Thursday.",exampleTranslation:"В четверг."},
    {topic:"time",word:"Friday",transcription:"[ˈfraɪ.deɪ]",translation:"пятница",example:"On Friday.",exampleTranslation:"В пятницу."},
    {topic:"time",word:"Saturday",transcription:"[ˈsæt.ə.deɪ]",translation:"суббота",example:"On Saturday.",exampleTranslation:"В субботу."},
    {topic:"time",word:"Sunday",transcription:"[ˈsʌn.deɪ]",translation:"воскресенье",example:"On Sunday.",exampleTranslation:"В воскресенье."},
    {topic:"time",word:"January",transcription:"[ˈdʒæn.ju.er.i]",translation:"январь",example:"In January.",exampleTranslation:"В январе."},
    {topic:"time",word:"February",transcription:"[ˈfeb.ru.er.i]",translation:"февраль",example:"In February.",exampleTranslation:"В феврале."},
    {topic:"time",word:"March",transcription:"[mɑːtʃ]",translation:"март",example:"In March.",exampleTranslation:"В марте."},
    {topic:"time",word:"April",transcription:"[ˈeɪ.prəl]",translation:"апрель",example:"In April.",exampleTranslation:"В апреле."},
    {topic:"time",word:"May",transcription:"[meɪ]",translation:"май",example:"In May.",exampleTranslation:"В мае."},
    {topic:"time",word:"June",transcription:"[dʒuːn]",translation:"июнь",example:"In June.",exampleTranslation:"В июне."},
    {topic:"time",word:"July",transcription:"[dʒuˈlaɪ]",translation:"июль",example:"In July.",exampleTranslation:"В июле."},
    {topic:"time",word:"August",transcription:"[ɔːˈɡʌst]",translation:"август",example:"In August.",exampleTranslation:"В августе."},
    {topic:"time",word:"September",transcription:"[sepˈtem.bər]",translation:"сентябрь",example:"In September.",exampleTranslation:"В сентябре."},
    {topic:"time",word:"October",transcription:"[ɒkˈtəʊ.bər]",translation:"октябрь",example:"In October.",exampleTranslation:"В октябре."},
    {topic:"time",word:"November",transcription:"[nəʊˈvem.bər]",translation:"ноябрь",example:"In November.",exampleTranslation:"В ноябре."},
    {topic:"time",word:"December",transcription:"[dɪˈsem.bər]",translation:"декабрь",example:"In December.",exampleTranslation:"В декабре."},
    {topic:"time",word:"spring",transcription:"[sprɪŋ]",translation:"весна",example:"In spring.",exampleTranslation:"Весной."},
    {topic:"time",word:"summer",transcription:"[ˈsʌm.ər]",translation:"лето",example:"In summer.",exampleTranslation:"Летом."},
    {topic:"time",word:"autumn",transcription:"[ˈɔː.təm]",translation:"осень",example:"In autumn.",exampleTranslation:"Осенью."},
    {topic:"time",word:"winter",transcription:"[ˈwɪn.tər]",translation:"зима",example:"In winter.",exampleTranslation:"Зимой."},
    {topic:"time",word:"past",transcription:"[pɑːst]",translation:"прошлое",example:"In the past.",exampleTranslation:"В прошлом."},
    {topic:"time",word:"present",transcription:"[ˈprez.ənt]",translation:"настоящее",example:"In the present.",exampleTranslation:"В настоящем."},
    {topic:"time",word:"future",transcription:"[ˈfjuː.tʃər]",translation:"будущее",example:"In the future.",exampleTranslation:"В будущем."},
    {topic:"time",word:"now",transcription:"[naʊ]",translation:"сейчас",example:"Do it now.",exampleTranslation:"Сделай это сейчас."},
    {topic:"time",word:"then",transcription:"[ðen]",translation:"тогда",example:"See you then.",exampleTranslation:"Увидимся тогда."},
    {topic:"time",word:"early",transcription:"[ˈɜː.li]",translation:"рано",example:"Wake up early.",exampleTranslation:"Проснись рано."},
    {topic:"time",word:"late",transcription:"[leɪt]",translation:"поздно",example:"Stay up late.",exampleTranslation:"Ложись поздно."},
    {topic:"time",word:"soon",transcription:"[suːn]",translation:"скоро",example:"See you soon.",exampleTranslation:"Скоро увидимся."},
    {topic:"time",word:"always",transcription:"[ˈɔːl.weɪz]",translation:"всегда",example:"Always smile.",exampleTranslation:"Всегда улыбайся."},
    {topic:"time",word:"never",transcription:"[ˈnev.ər]",translation:"никогда",example:"Never give up.",exampleTranslation:"Никогда не сдавайся."},
    {topic:"time",word:"calendar",transcription:"[ˈkæl.ɪn.dər]",translation:"календарь",example:"Check the calendar.",exampleTranslation:"Проверь календарь."}
  ],
  verbs: {
    work:  { base:"work",  past:"worked",  participle:"worked",  ing:"working",  regular:true,  thirdSingular:"works" },
    go:    { base:"go",    past:"went",    participle:"gone",    ing:"going",    regular:false, thirdSingular:"goes" },
    speak: { base:"speak", past:"spoke",   participle:"spoken",  ing:"speaking", regular:false, thirdSingular:"speaks" },
    eat:   { base:"eat",   past:"ate",     participle:"eaten",   ing:"eating",   regular:false, thirdSingular:"eats" },
    sleep: { base:"sleep", past:"slept",   participle:"slept",   ing:"sleeping", regular:false, thirdSingular:"sleeps" },
    run:   { base:"run",   past:"ran",     participle:"run",     ing:"running",  regular:false, thirdSingular:"runs" },
    write: { base:"write", past:"wrote",   participle:"written", ing:"writing",  regular:false, thirdSingular:"writes" },
    read:  { base:"read",  past:"read",    participle:"read",    ing:"reading",  regular:false, thirdSingular:"reads" },
    want:  { base:"want",  past:"wanted",  participle:"wanted",  ing:"wanting",  regular:true,  thirdSingular:"wants" },
    look:  { base:"look",  past:"looked",  participle:"looked",  ing:"looking",  regular:true,  thirdSingular:"looks" },
    use:   { base:"use",   past:"used",    participle:"used",    ing:"using",    regular:true,  thirdSingular:"uses" },
    call:  { base:"call",  past:"called",  participle:"called",  ing:"calling",  regular:true,  thirdSingular:"calls" },
    try:   { base:"try",   past:"tried",   participle:"tried",   ing:"trying",   regular:true,  thirdSingular:"tries" },
    ask:   { base:"ask",   past:"asked",   participle:"asked",   ing:"asking",   regular:true,  thirdSingular:"asks" },
    need:  { base:"need",  past:"needed",  participle:"needed",  ing:"needing",  regular:true,  thirdSingular:"needs" },
    seem:  { base:"seem",  past:"seemed",  participle:"seemed",  ing:"seeming",  regular:true,  thirdSingular:"seems" },
    help:  { base:"help",  past:"helped",  participle:"helped",  ing:"helping",  regular:true,  thirdSingular:"helps" },
    talk:  { base:"talk",  past:"talked",  participle:"talked",  ing:"talking",  regular:true,  thirdSingular:"talks" },
    turn:  { base:"turn",  past:"turned",  participle:"turned",  ing:"turning",  regular:true,  thirdSingular:"turns" },
    start: { base:"start", past:"started", participle:"started", ing:"starting", regular:true,  thirdSingular:"starts" },
    play:  { base:"play",  past:"played",  participle:"played",  ing:"playing",  regular:true,  thirdSingular:"plays" },
    move:  { base:"move",  past:"moved",   participle:"moved",   ing:"moving",   regular:true,  thirdSingular:"moves" },
    live:  { base:"live",  past:"lived",   participle:"lived",   ing:"living",   regular:true,  thirdSingular:"lives" },
    believe:{base:"believe",past:"believed",participle:"believed",ing:"believing",regular:true, thirdSingular:"believes"},
    happen:{ base:"happen",past:"happened",participle:"happened",ing:"happening",regular:true,  thirdSingular:"happens"},
    provide:{base:"provide",past:"provided",participle:"provided",ing:"providing",regular:true, thirdSingular:"provides"},
    be:    { base:"be",    past:"was/were",participle:"been",    ing:"being",    regular:false, thirdSingular:"is" },
    have:  { base:"have",  past:"had",     participle:"had",     ing:"having",   regular:false, thirdSingular:"has" },
    do:    { base:"do",    past:"did",     participle:"done",    ing:"doing",    regular:false, thirdSingular:"does" },
    say:   { base:"say",   past:"said",    participle:"said",    ing:"saying",   regular:false, thirdSingular:"says" },
    get:   { base:"get",   past:"got",     participle:"got",     ing:"getting",  regular:false, thirdSingular:"gets" },
    make:  { base:"make",  past:"made",    participle:"made",    ing:"making",   regular:false, thirdSingular:"makes" },
    know:  { base:"know",  past:"knew",    participle:"known",   ing:"knowing",  regular:false, thirdSingular:"knows" },
    think: { base:"think", past:"thought", participle:"thought", ing:"thinking", regular:false, thirdSingular:"thinks" },
    take:  { base:"take",  past:"took",    participle:"taken",   ing:"taking",   regular:false, thirdSingular:"takes" },
    see:   { base:"see",   past:"saw",     participle:"seen",    ing:"seeing",   regular:false, thirdSingular:"sees" },
    come:  { base:"come",  past:"came",    participle:"come",    ing:"coming",   regular:false, thirdSingular:"comes" },
    find:  { base:"find",  past:"found",   participle:"found",   ing:"finding",  regular:false, thirdSingular:"finds" },
    give:  { base:"give",  past:"gave",    participle:"given",   ing:"giving",   regular:false, thirdSingular:"gives" },
    tell:  { base:"tell",  past:"told",    participle:"told",    ing:"telling",  regular:false, thirdSingular:"tells" },
    feel:  { base:"feel",  past:"felt",    participle:"felt",    ing:"feeling",  regular:false, thirdSingular:"feels" },
    become:{ base:"become",past:"became",  participle:"become",  ing:"becoming", regular:false, thirdSingular:"becomes" },
    leave: { base:"leave", past:"left",    participle:"left",    ing:"leaving",  regular:false, thirdSingular:"leaves" },
    put:   { base:"put",   past:"put",     participle:"put",     ing:"putting",  regular:false, thirdSingular:"puts" },
    mean:  { base:"mean",  past:"meant",   participle:"meant",   ing:"meaning",  regular:false, thirdSingular:"means" },
    keep:  { base:"keep",  past:"kept",    participle:"kept",    ing:"keeping",  regular:false, thirdSingular:"keeps" },
    let:   { base:"let",   past:"let",     participle:"let",     ing:"letting",  regular:false, thirdSingular:"lets" },
    begin: { base:"begin", past:"began",   participle:"begun",   ing:"beginning",regular:false, thirdSingular:"begins" },
    show:  { base:"show",  past:"showed",  participle:"shown",   ing:"showing",  regular:false, thirdSingular:"shows" },
    hear:  { base:"hear",  past:"heard",   participle:"heard",   ing:"hearing",  regular:false, thirdSingular:"hears" },
    bring: { base:"bring", past:"brought", participle:"brought", ing:"bringing", regular:false, thirdSingular:"brings" },
    sit:   { base:"sit",   past:"sat",     participle:"sat",     ing:"sitting",  regular:false, thirdSingular:"sits" },
    stand: { base:"stand", past:"stood",   participle:"stood",   ing:"standing", regular:false, thirdSingular:"stands" },
    lose:  { base:"lose",  past:"lost",    participle:"lost",    ing:"losing",   regular:false, thirdSingular:"loses" },
    pay:   { base:"pay",   past:"paid",    participle:"paid",    ing:"paying",   regular:false, thirdSingular:"pays" },
    meet:  { base:"meet",  past:"met",     participle:"met",     ing:"meeting",  regular:false, thirdSingular:"meets" },
    teach: { base:"teach", past:"taught",  participle:"taught",  ing:"teaching", regular:false, thirdSingular:"teaches" },
    drink: { base:"drink", past:"drank",   participle:"drunk",   ing:"drinking", regular:false, thirdSingular:"drinks" },
    drive: { base:"drive", past:"drove",   participle:"driven",  ing:"driving",  regular:false, thirdSingular:"drives" },
    sing:  { base:"sing",  past:"sang",    participle:"sung",    ing:"singing",  regular:false, thirdSingular:"sings" },
    swim:  { base:"swim",  past:"swam",    participle:"swum",    ing:"swimming", regular:false, thirdSingular:"swims" }
  }
};